// Korean for every string the plugin shows, and for the EUD catalogue's words; English is the key. Map text, names from the map and the game's own names are never translated.
// `tests/ko.test.ts` fails on a `t("…")` / `msg("…")` in the source or a catalogue string with no entry here, and on an entry nothing uses.
export const KO: Record<string, string> = {
  " (each cycle)": " (매 주기)",
  "(no text)": "(텍스트 없음)",
  "0 for any distance": "0이면 거리 제한 없음",
  "0 means all": "0은 모두",
  "0x{hex}, one bit": "0x{hex}, 1비트",
  "16-bit (up to 65,535)": "16비트 (65,535까지)",
  "24 cycles a second": "1초에 24주기",
  "32-bit (any count)": "32비트 (제한 없음)",
  "A build row names location {n}, which the map no longer has.": "빌드 행이 맵에서 없어진 로케이션 {n}을(를) 가리킵니다.",
  "A build row no trigger uses is still in the map's Magenta data; it is sent, and never fires.": "어느 트리거도 쓰지 않는 빌드 행이 맵의 Magenta 데이터에 남아 있습니다. 빌드에 들어가지만 실행되지 않습니다.",
  "A build row runs here in the game; the dry run skips it.": "게임에서는 여기서 빌드 행이 실행됩니다. 모의 실행은 건너뜁니다.",
  "a computer": "컴퓨터",
  "a computer (lobby)": "컴퓨터 (로비)",
  "a cycle is {s} s": "한 주기는 {s}초",
  "a defensive matrix": "디펜시브 매트릭스",
  "a detector": "탐지기",
  "A floating panel is dragged about and resized from its corner; a docked one sits in the right dock with the Layers and Properties panels and stacks the list over the trigger.": "띄운 패널은 끌어서 옮기고 모서리로 크기를 조절합니다. 도킹한 패널은 레이어, 속성 패널과 함께 오른쪽 도크에 놓이며 목록을 트리거 위에 쌓아 보여 줍니다.",
  "a hero": "영웅",
  "a human": "사람",
  "A key gives minerals": "키를 누르면 미네랄",
  "a location": "로케이션",
  "A message cannot contain : or =.": "메시지에는 : 이나 = 를 쓸 수 없습니다.",
  "A Never condition means it never fires.": "Never 조건이 있어서 실행되지 않습니다.",
  "A Never condition means this trigger never fires.": "Never 조건이 있어서 이 트리거는 실행되지 않습니다.",
  "A new trigger after the selected one (Ctrl+N)": "선택한 트리거 뒤에 새 트리거 (Ctrl+N)",
  "A note on this trigger; the game does nothing with it": "이 트리거에 대한 메모. 게임에서는 아무 일도 하지 않습니다",
  "A number instead of a counter": "카운터 대신 숫자",
  "A pattern is ^start.*end$ or ^start.*middle.*end$.": "패턴은 ^시작.*끝$ 또는 ^시작.*중간.*끝$ 형식입니다.",
  "A player clicked (synced)": "플레이어가 클릭함 (동기화)",
  "A player pressed a key (synced)": "플레이어가 키를 누름 (동기화)",
  "A player who brings a unit to the location is given the units standing on it. Change the location, the unit and its owner.": "로케이션에 유닛을 가져온 플레이어가 그 위에 있는 유닛을 받습니다. 로케이션, 유닛, 소유자를 바꾸세요.",
  "A player with a unit at the location for thirty seconds wins. Uses a switch as the clock; change the location and the seconds.": "로케이션에 30초 동안 유닛을 둔 플레이어가 승리합니다. 스위치를 시계로 씁니다. 로케이션과 초를 바꾸세요.",
  "A player with no units and no buildings left is defeated.": "유닛과 건물이 하나도 남지 않은 플레이어가 패배합니다.",
  "A player's mouse is over a location (synced)": "플레이어의 마우스가 로케이션 위에 있음 (동기화)",
  "A player's mouse…": "플레이어 마우스…",
  "a random number below": "다음 미만의 무작위 수",
  "A small box is centred on the unit once this cycle's triggers have all run, so a trigger in the next cycle can act on it through the location. A row below this one in the same trigger still sees the location where it was.": "이번 주기의 트리거가 모두 실행된 뒤 작은 상자가 유닛 중심에 놓이므로, 다음 주기의 트리거가 그 로케이션으로 유닛을 다룰 수 있습니다. 같은 트리거에서 이 행 아래에 있는 행은 아직 원래 자리의 로케이션을 봅니다.",
  "A sound plays here.": "여기서 사운드가 재생됩니다.",
  "A ten-minute countdown, then victory for everyone still in. Change the seconds, or Victory to Defeat.": "10분 카운트다운이 끝나면 남아 있는 모두가 승리합니다. 초를 바꾸거나 Victory를 Defeat로 바꾸세요.",
  "A trigger at the end of the list now sets the trigger timer to 0 every cycle, so the whole list runs every frame instead of every two seconds. Every Wait and every preserved trigger in the map now runs on that clock: a counter that added 1 per cycle adds 24 a second.": "이제 목록 끝의 트리거가 매 주기 트리거 타이머를 0으로 설정하므로, 목록 전체가 2초마다가 아니라 매 프레임 실행됩니다. 맵의 모든 Wait과 보존된 트리거가 이 시계로 실행됩니다. 주기마다 1씩 더하던 카운터는 1초에 24씩 더합니다.",
  "A unit check no trigger uses is still in the map's Magenta data; it is sent, and never fires.": "어느 트리거도 쓰지 않는 유닛 검사가 맵의 Magenta 데이터에 남아 있습니다. 빌드에 들어가지만 실행되지 않습니다.",
  "A Unit Properties slot, 1 to 64; 0 for none": "유닛 속성 슬롯, 1–64. 0이면 없음",
  "A units.dat flag, bit 14. Verified as a write and read (probe 9); what the game does with it for a type that never had it was not checked — the flag alone gives no button.": "units.dat 플래그, 비트 14. 쓰기와 읽기를 확인했습니다 (probe 9). 원래 이 플래그가 없던 종류에 게임이 무엇을 하는지는 확인하지 않았습니다. 플래그만으로는 버튼이 생기지 않습니다.",
  "A units.dat flag, bit 20. Verified as a write and read (probe 9); what the game does with it for a type that never had it was not checked — the flag alone gives no button.": "units.dat 플래그, 비트 20. 쓰기와 읽기를 확인했습니다 (probe 9). 원래 이 플래그가 없던 종류에 게임이 무엇을 하는지는 확인하지 않았습니다. 플래그만으로는 버튼이 생기지 않습니다.",
  "A units.dat flag, bit 6. Verified as a write and read (probe 9); what the game does with it for a type that never had it was not checked — the flag alone gives no button.": "units.dat 플래그, 비트 6. 쓰기와 읽기를 확인했습니다 (probe 9). 원래 이 플래그가 없던 종류에 게임이 무엇을 하는지는 확인하지 않았습니다. 플래그만으로는 버튼이 생기지 않습니다.",
  "A units.dat flag, bit 9. Verified as a write and read (probe 9); what the game does with it for a type that never had it was not checked — the flag alone gives no button.": "units.dat 플래그, 비트 9. 쓰기와 읽기를 확인했습니다 (probe 9). 원래 이 플래그가 없던 종류에 게임이 무엇을 하는지는 확인하지 않았습니다. 플래그만으로는 버튼이 생기지 않습니다.",
  "A units.dat flag. Units of the type see cloaked and burrowed units in their sight range.": "units.dat 플래그. 이 종류의 유닛이 시야 안의 은폐 유닛과 버로우 유닛을 봅니다.",
  "A units.dat flag. Verified on marines already on the map: their hit points climbed at once (probe 8).": "units.dat 플래그. 이미 맵에 있는 마린으로 확인: 체력이 바로 차올랐습니다 (probe 8).",
  "A units.dat flag. Verified: a medic healed a vulture flagged organic (probe 9), one already on the map.": "units.dat 플래그. 확인됨: 메딕이 생체 플래그를 붙인 벌처를 치료했습니다 (probe 9). 이미 맵에 있던 벌처입니다.",
  "A units.dat flag. Verified: an SCV could repair a marine flagged mechanical (probe 9), one already on the map.": "units.dat 플래그. 확인됨: SCV가 기계 플래그를 붙인 마린을 수리할 수 있었습니다 (probe 9). 이미 맵에 있던 마린입니다.",
  "A units.dat flag: units made after this cannot be hurt; the ones already on the map keep what they were made with (probe 8).": "units.dat 플래그: 이후에 만든 유닛은 피해를 입지 않고, 이미 맵에 있는 유닛은 만들어질 때의 값을 유지합니다 (probe 8).",
  "A units.dat flag: units made after this have it; the ones already on the map keep what they were made with.": "units.dat 플래그: 이후에 만든 유닛에 적용되고, 이미 맵에 있는 유닛은 만들어질 때의 값을 유지합니다.",
  "A Wait in a preserved trigger holds up every other trigger of its owner while it waits, every cycle.": "보존된 트리거의 Wait은 기다리는 동안 매 주기 소유자의 다른 트리거를 모두 멈춥니다.",
  "able to burrow": "버로우 가능",
  "able to cloak": "은폐 가능",
  "About 24 a second at Fastest, 15 at Normal. Verified: a line at 10 s (probe 8).": "가장 빠름에서 1초에 약 24, 보통에서 15. 확인됨: 10초에 한 줄 (probe 8).",
  "above": "초과",
  "Action": "액션",
  "Action {n}": "액션 {n}",
  "Actions": "액션",
  "Add": "추가",
  "Add a condition…": "조건 추가…",
  "Add a counter to another": "카운터를 다른 카운터에 더하기",
  "Add a player or group": "플레이어나 그룹 추가",
  "Add action": "액션 추가",
  "Add an action…": "액션 추가…",
  "Add build row": "빌드 행 추가",
  "Add chat command": "채팅 명령 추가",
  "Add comparison": "비교 추가",
  "Add condition": "조건 추가",
  "Add counter step": "카운터 단계 추가",
  "Add input": "입력 추가",
  "Add recipe": "레시피 추가",
  "Add unit check": "유닛 검사 추가",
  "Add {Amount} to the hangar of {Count} {Unit} owned by {Player} at {Location}": "{Location}에 있는 {Player}의 {Unit} {Count}의 격납고에 {Amount} 추가",
  "Add {from} to {to}": "{to}에 {from} 더하기",
  "Add {name}": "{name} 추가",
  "Address 0x{hex}…": "주소 0x{hex}…",
  "Air units pass through one another": "공중 유닛끼리 겹쳐 지나감",
  "Air weapon of a unit type": "유닛 종류의 공중 무기",
  "all": "모두",
  "All 16 condition slots are used.": "조건 16칸을 모두 썼습니다.",
  "All 64 action slots are used.": "액션 64칸을 모두 썼습니다.",
  "Alliance of a player toward another": "다른 플레이어에 대한 동맹 관계",
  "Allied Victory": "동맹 승리",
  "allied victory": "동맹 승리",
  "Ally": "동맹",
  "ally": "동맹",
  "Always": "항상",
  "Always Display": "항상 표시",
  "Amount": "양",
  "An AI script runs here in the game; the dry run does not have one.": "게임에서는 여기서 AI 스크립트가 실행됩니다. 모의 실행에는 AI가 없습니다.",
  "An order is given here; the dry run does not move units.": "여기서 명령이 내려집니다. 모의 실행은 유닛을 움직이지 않습니다.",
  "Animate the portrait in {Slot} for {Duration} ms": "{Slot}의 초상화를 {Duration}ms 동안 움직임",
  "Answered by a run of generated triggers before this one, every cycle; they are hidden here and locked in the other editors.": "매 주기 이 트리거 앞에서 만들어진 트리거들이 답을 냅니다. 여기서는 숨겨지고 다른 편집기에서는 잠깁니다.",
  "any distance": "거리 제한 없음",
  "Any player, any unit; fires again each time": "모든 플레이어, 모든 유닛. 올 때마다 다시 실행됩니다",
  "any unit": "모든 유닛",
  "Any unit of a kind has a stat below or above": "어떤 종류의 유닛 하나라도 능력치가 기준 미만 또는 초과",
  "Any {units} has {field} {cmp} {value}": "{units} 중 하나라도 {field} {value} {cmp}",
  "Any {units} {is} {field}": "{units} 중 하나라도 {field}: {is}",
  "anyone": "누구든",
  "anywhere": "어디든",
  "apply a spell effect": "마법 효과 걸기",
  "Armor of a unit type": "유닛 종류의 방어력",
  "as": "플레이어:",
  "As a condition this reads what Set Alliance Status wrote; the game has no native way to test it. Verified both ways in probe 9. The catalogue had this at 0x58D6F8 until 2026-09-14, which is the game clock.": "조건으로는 Set Alliance Status가 쓴 값을 읽습니다. 게임에는 이것을 검사하는 기본 방법이 없습니다. probe 9에서 양쪽 모두 확인했습니다. 카탈로그는 2026-09-14까지 이것을 게임 시계인 0x58D6F8로 잘못 두었습니다.",
  "as {player}": "플레이어: {player}",
  "At least": "이상",
  "at least": "이상",
  "At most": "이하",
  "at most": "이하",
  "at random": "무작위",
  "At the start, set the Marine's max hit points to 80 and its armor to 2. EUD writes; add rows for other stats.": "시작할 때 마린의 최대 체력을 80, 방어력을 2로 설정합니다. EUD 쓰기입니다. 다른 능력치는 행을 추가하세요.",
  "attack": "공격",
  "being downloaded": "다운로드 중",
  "below": "미만",
  "blue": "파랑",
  "brown": "갈색",
  "Build": "빌드",
  "Build EUD map": "EUD 맵 빌드",
  "Build EUD map…": "EUD 맵 빌드…",
  "Build options": "빌드 옵션",
  "Build time of a unit type": "유닛 종류의 생산 시간",
  "Build · {n} · {state}": "빌드 · {n} · {state}",
  "Buildings": "건물",
  "Building…": "빌드 중…",
  "Builds run with eudplib {eudplib} and euddraft {euddraft}, {where}.": "빌드는 eudplib {eudplib}과(와) euddraft {euddraft}(으)로 실행됩니다. {where}.",
  "Build…": "빌드…",
  "built": "빌드됨",
  "Built from the map as it is now, {when}{file}.": "지금의 맵으로 빌드했습니다. {when}{file}.",
  "Built, but not saved.": "빌드했지만 저장하지 않았습니다.",
  "Built: {name}, {kb} KB in {s} s.": "빌드 완료: {name}, {kb} KB, {s}초.",
  "Burrow ability flag of a unit type": "유닛 종류의 버로우 능력 플래그",
  "burrowed": "버로우 상태",
  "Cancel": "취소",
  "Cannot tell": "알 수 없음",
  "center a location on it": "로케이션을 유닛 중심에",
  "Center the view on {Location}": "화면을 {Location|으로} 이동",
  "Center {Move} on {Unit} owned by {Player} at {Unit at}": "{Move|을} {Unit at}에 있는 {Player}의 {Unit} 중심으로 옮김",
  "Change a unit type's stats": "유닛 종류 능력치 바꾸기",
  "Change button": "버튼 바꾸기",
  "Change key": "키 바꾸기",
  "Change location": "로케이션 바꾸기",
  "Change owners": "소유자 바꾸기",
  "changed and read by": "바꾸고 읽는 트리거:",
  "changed by": "바꾸는 트리거:",
  "Changes the owner byte only: the unit turns hostile or friendly at once, but keeps its old colour (that lives on its sprite) and its selection and control groups. Give Units is the clean way. Verified in Remastered 2026-09-12. Slots: the first placed unit is slot 0 and later ones count down from 1699 (verified in Remastered 2026-09-12); the chip picks a unit on the map and works the slot out. Start locations take no slot; nor does a unit of a human player who is not in the game (it is removed at load), so slots after one shift by one when that player is missing.": "소유자 바이트만 바꿉니다. 유닛은 바로 적이나 아군이 되지만, 예전 색(스프라이트에 있음)과 선택, 부대 지정은 그대로입니다. 깔끔하게 하려면 Give Units를 쓰세요. 2026-09-12 Remastered에서 확인됨. 슬롯: 처음 배치된 유닛이 슬롯 0이고 그 뒤로는 1699부터 거꾸로 셉니다 (2026-09-12 Remastered에서 확인). 칩에서 맵의 유닛을 고르면 슬롯을 계산해 줍니다. 시작 위치는 슬롯을 차지하지 않고, 게임에 없는 사람 플레이어의 유닛도 불러올 때 지워지므로 차지하지 않습니다. 그래서 그 플레이어가 없으면 뒤의 슬롯이 하나씩 밀립니다.",
  "chat message\u0004exactly": "그대로",
  "Classes": "분류",
  "clear": "해제",
  "Click a location": "로케이션을 클릭하세요",
  "Click a placed unit": "배치된 유닛을 클릭하세요",
  "Click a unit to take its type": "종류를 가져올 유닛을 클릭하세요",
  "click a value to change it": "값을 클릭해서 바꾸기",
  "Click to change": "클릭해서 바꾸기",
  "Click to change; hover to show on the map": "클릭해서 바꾸기, 가리키면 맵에 표시",
  "Click to clear": "클릭해서 끄기",
  "Click to remove": "클릭해서 제거",
  "Cloak ability flag of a unit type": "유닛 종류의 은폐 능력 플래그",
  "Cloak state of a placed unit": "배치된 유닛의 은폐 상태",
  "Close": "닫기",
  "closed": "닫힘",
  "collide again": "다시 충돌",
  "Colour of a player": "플레이어의 색",
  "Comment": "주석",
  "Comment {Text}": "주석 {Text}",
  "Compare two counters": "두 카운터 비교",
  "Comparison": "비교",
  "comparison\u0004exactly": "일치",
  "Condition {n}": "조건 {n}",
  "condition {n}": "조건 {n}",
  "Conditions": "조건",
  "Conditions {a} and {b} contradict each other: at least {lo} and at most {hi}.": "조건 {a}과(와) {b}이(가) 서로 모순됩니다: {lo} 이상이면서 {hi} 이하입니다.",
  "Conditions {a} and {b} contradict each other: exactly {x} and exactly {y}.": "조건 {a}과(와) {b}이(가) 서로 모순됩니다: 정확히 {x}이면서 정확히 {y}입니다.",
  "Cooldown of a weapon": "무기의 재사용 대기시간",
  "Copied as text": "텍스트로 복사했습니다",
  "Copy a counter into another": "카운터를 다른 카운터에 복사",
  "Copy trigger as text": "트리거를 텍스트로 복사",
  "Copy {from} into {to}": "{from|을} {to}에 복사",
  "Count": "수",
  "Count units into a counter": "유닛 수를 카운터에 세기",
  "Countdown that ends the game": "게임을 끝내는 카운트다운",
  "Countdown timer": "카운트다운 타이머",
  "Countdown timer is {Comparison} {Amount} seconds": "카운트다운 타이머가 {Amount}초 {Comparison}",
  "Counter": "카운터",
  "Counter name": "카운터 이름",
  "Counters": "카운터",
  "Counters…": "카운터…",
  "Create units at {location}": "{location}에 유닛 생성",
  "Create {Count} {Unit} at {Location} for {Player}": "{Location}에 {Player}의 {Unit} {Count} 생성",
  "Create {Count} {Unit} at {Location} for {Player} with {Properties}": "{Location}에 {Player}의 {Unit} {Count} 생성, {Properties}",
  "Ctrl+Enter to apply": "Ctrl+Enter로 적용",
  "Current player commands the least {Unit}": "현재 플레이어가 {Unit|을} 가장 적게 보유",
  "Current player commands the least {Unit} at {Location}": "현재 플레이어가 {Location}에서 {Unit|을} 가장 적게 보유",
  "Current player commands the most {Unit}": "현재 플레이어가 {Unit|을} 가장 많이 보유",
  "Current player commands the most {Unit} at {Location}": "현재 플레이어가 {Location}에서 {Unit|을} 가장 많이 보유",
  "Current player has the fewest kills of {Unit}": "현재 플레이어의 {Unit} 처치 수가 가장 적음",
  "Current player has the highest {Score} score": "현재 플레이어의 {Score} 점수가 가장 높음",
  "Current player has the least {Resource}": "현재 플레이어의 {Resource|이} 가장 적음",
  "Current player has the lowest {Score} score": "현재 플레이어의 {Score} 점수가 가장 낮음",
  "Current player has the most kills of {Unit}": "현재 플레이어의 {Unit} 처치 수가 가장 많음",
  "Current player has the most {Resource}": "현재 플레이어의 {Resource|이} 가장 많음",
  "Current Player is whichever owner is running it.": "Current Player는 이 트리거를 실행하고 있는 소유자입니다.",
  "Custom": "사용자 지정",
  "cycle {n} · {s} s": "주기 {n} · {s}초",
  "Damage bonus per upgrade of a weapon": "무기의 업그레이드당 추가 공격력",
  "Damage factor of a weapon": "무기의 공격 횟수",
  "Damage of a weapon": "무기의 공격력",
  "Defeat when nothing is left": "남은 것이 없으면 패배",
  "Delete trigger": "트리거 삭제",
  "Detector flag of a unit type": "유닛 종류의 탐지기 플래그",
  "Differs per computer: what follows runs for that player's screen only, so keep it to text, sounds and the view.": "컴퓨터마다 다릅니다. 뒤에 오는 것은 그 플레이어의 화면에서만 실행되므로 텍스트, 사운드, 화면 이동에만 쓰세요.",
  "disable": "사용 안 함",
  "Disable": "끄기",
  "Disable / enable trigger": "트리거 끄기 / 켜기",
  "Disable debug mode": "디버그 모드 끄기",
  "Display": "표시",
  "Display {Text} ({Display})": "{Text} 표시 ({Display})",
  "divided by": "÷",
  "do nothing to it": "아무것도 안 함",
  "Dock on the right": "오른쪽에 도킹",
  "Docked on the right": "오른쪽에 도킹",
  "Don't Always Display": "항상 표시 안 함",
  "Done by a run of {n} generated triggers right after this one, in the same cycle: this trigger's own rows run first, the triggers after the run see the result. The run is hidden here and locked in the other editors.": "같은 주기에 이 트리거 바로 뒤에서 만들어진 트리거 {n}개가 처리합니다. 이 트리거의 행이 먼저 실행되고, 그 뒤의 트리거들이 결과를 봅니다. 만들어진 트리거는 여기서 숨겨지고 다른 편집기에서는 잠깁니다.",
  "Double-click to rename; drop a trigger here to put it in the folder": "더블클릭해서 이름 바꾸기. 트리거를 여기에 놓으면 폴더에 넣습니다",
  "down by": "빼기:",
  "downloaded on the first build, {mb} MB": "첫 빌드 때 다운로드, {mb} MB",
  "Drag to resize the list; double-click to hide it": "끌어서 목록 크기 조절, 더블클릭하면 숨기기",
  "draw": "무승부",
  "draws": "무승부",
  "Drop it and start over": "버리고 새로 시작",
  "Drop Magenta's data": "Magenta 데이터 버리기",
  "Dry run…": "모의 실행…",
  "Duplicate trigger": "트리거 복제",
  "Duration": "시간",
  "Edit action": "액션 편집",
  "Edit build row": "빌드 행 편집",
  "Edit chat command": "채팅 명령 편집",
  "Edit comparison": "비교 편집",
  "Edit condition": "조건 편집",
  "Edit counter step": "카운터 단계 편집",
  "Edit trigger": "트리거 편집",
  "Edit unit check": "유닛 검사 편집",
  "Elapsed game time is {Comparison} {Amount} seconds": "게임 경과 시간이 {Amount}초 {Comparison}",
  "empty": "비어 있음",
  "Empty trigger": "빈 트리거",
  "enable": "사용",
  "Enable": "켜기",
  "Enable debug mode": "디버그 모드 켜기",
  "Enable Skip Tutorial": "튜토리얼 건너뛰기 켜기",
  "End the scenario in a draw": "시나리오를 무승부로 끝냄",
  "End the scenario in defeat": "시나리오를 패배로 끝냄",
  "End the scenario in victory": "시나리오를 승리로 끝냄",
  "Enemy": "적",
  "enemy": "적",
  "energy": "에너지",
  "energy %": "에너지 %",
  "Energy cost of a technology": "기술의 에너지 비용",
  "Energy of a placed unit": "배치된 유닛의 에너지",
  "ensnare": "인스네어",
  "equal to": "동일",
  "EUD player": "EUD 플레이어",
  "euddraft adds the code for the rows below to the map as it stands, here in the editor, and the built map is saved as a file. Nothing leaves this machine. Only StarCraft: Remastered plays the result. Keep this map as the source: the built one is the compiled output, the way a program is.": "euddraft가 아래 행들의 코드를 지금의 맵에 더하고, 빌드한 맵을 파일로 저장합니다. 모두 이 편집기 안에서 일어나며 이 컴퓨터 밖으로 나가는 것은 없습니다. 결과물은 StarCraft: Remastered에서만 실행됩니다. 이 맵을 원본으로 보관하세요. 빌드한 맵은 프로그램처럼 컴파일된 결과물입니다.",
  "Every build row's sentence, every folder and every counter name in it is lost; the triggers themselves stay as they are in the map. Continue?": "데이터에 있는 빌드 행의 문장, 폴더, 카운터 이름이 모두 사라집니다. 트리거 자체는 맵에 그대로 남습니다. 계속할까요?",
  "Every enemy unit that dies pays the players 50 minerals. Change the enemy player and the unit, or the amount.": "적 유닛이 죽을 때마다 플레이어가 미네랄 50을 받습니다. 적 플레이어와 유닛, 또는 양을 바꾸세요.",
  "every frame": "매 프레임",
  "Every owner runs this trigger, and its switch is shared: when the Current Player condition is false for one of them, that run can flip the switch for the others. Guard with a death counter of the Current Player instead.": "모든 소유자가 이 트리거를 실행하는데 스위치는 모두가 함께 씁니다. 한 소유자에게 Current Player 조건이 거짓이어도 그 실행이 다른 소유자의 스위치를 바꿀 수 있습니다. 대신 Current Player의 데스 카운터로 막으세요.",
  "Every player runs this trigger, each on their own.": "모든 플레이어가 각자 이 트리거를 실행합니다.",
  "Every player's units in the location, on the first cycle": "첫 주기에 로케이션 안에 있는 모든 플레이어의 유닛",
  "Every sixty seconds four Marines appear at the location for Player 8. Change the unit, the count, the player and the location.": "60초마다 로케이션에 Player 8의 마린 4기가 나타납니다. 유닛, 수, 플레이어, 로케이션을 바꾸세요.",
  "every two seconds": "2초마다",
  "everyone": "모두",
  "Exactly": "정확히",
  "Extra damage per upgrade level. Verified (probe 9).": "업그레이드 단계당 추가 공격력. 확인됨 (probe 9).",
  "Fast": "빠름",
  "Faster": "더 빠름",
  "Fastest": "가장 빠름",
  "Filter…": "필터…",
  "fired and done": "실행하고 끝남",
  "fired {n} times so far": "지금까지 {n}번 실행됨",
  "fires {trigger}": "{trigger} 실행",
  "Floating over the map": "맵 위에 띄우기",
  "Fold": "접기",
  "Folder name": "폴더 이름",
  "followed by a number": "뒤에 숫자",
  "For each unit of a kind": "어떤 종류의 유닛 각각에",
  "For each {units}: {action}": "{units} 각각: {action}",
  "Four records: the unit's flingy is switched to table control and given this top speed, with acceleration and stopping distance to match. Units made after this move at the new speed; the ones already on the map keep theirs. A Marine walks at 4, a Vulture at 6.7. Hero units that share a type's flingy change with it.": "레코드 4개: 유닛의 flingy를 테이블 제어로 바꾸고 이 최고 속도를 주며, 가속도와 정지 거리도 맞춥니다. 이후에 만든 유닛은 새 속도로 움직이고, 이미 맵에 있는 유닛은 원래 속도를 유지합니다. 마린은 4, 벌처는 6.7로 움직입니다. 같은 flingy를 쓰는 영웅 유닛도 함께 바뀝니다.",
  "frames": "프레임",
  "Frames the game has run": "게임이 진행된 프레임",
  "From": "출발",
  "Game": "게임",
  "Game speed": "게임 속도",
  "gas": "가스",
  "Gas cost of a technology": "기술의 가스 비용",
  "Gas cost of a unit type": "유닛 종류의 가스 비용",
  "Gas cost of an upgrade": "업그레이드의 가스 비용",
  "Gas of a player": "플레이어의 가스",
  "Generated by {what}: edit it there, not here.": "{what}이(가) 만든 트리거입니다. 여기가 아니라 그쪽에서 편집하세요.",
  "give": "회복",
  "give the speed upgrade": "속도 업그레이드 주기",
  "Give this death counter a name, and use it by name everywhere": "이 데스 카운터에 이름을 붙이고 어디서나 이름으로 씁니다",
  "Give this {unit} to the player who comes": "찾아온 플레이어에게 이 {unit} 주기",
  "give to": "넘겨주기:",
  "Give units at a beacon": "비컨에서 유닛 주기",
  "Give {Count} {Unit} owned by {From} at {Location} to {To}": "{Location}에 있는 {From}의 {Unit} {Count|을} {To}에게 줌",
  "Goal": "목표",
  "greater than": "초과",
  "green": "초록",
  "Ground weapon of a unit type": "유닛 종류의 지상 무기",
  "hallucinate": "환영으로",
  "Hallucination flag of a placed unit": "배치된 유닛의 환영 플래그",
  "has left the game": "게임을 나감",
  "has not fired yet": "아직 실행되지 않음",
  "has {n}": "현재 {n}",
  "held (not seen in the game)": "누르고 있음 (게임에서 확인 안 됨)",
  "Hero flag of a unit type": "유닛 종류의 영웅 플래그",
  "Hex address the player value should reach through the deaths table (Deaths and Set Deaths only)": "플레이어 값이 데스 테이블을 거쳐 가리킬 16진수 주소 (Deaths와 Set Deaths만)",
  "Hide the portrait in {Slot}": "{Slot}의 초상화 숨기기",
  "hit points": "체력",
  "hit points %": "체력 %",
  "Hit points of a placed unit": "배치된 유닛의 체력",
  "Hits per attack. Verified (probe 9).": "공격 한 번의 타격 횟수. 확인됨 (probe 9).",
  "hold fire": "공격 중지",
  "How far a unit looks for targets on its own. A write of 1 in probe 9 could not be read back; not yet seen working.": "유닛이 스스로 대상을 찾는 거리입니다. probe 9에서 1을 쓴 값을 다시 읽지 못했습니다. 아직 동작을 확인하지 않았습니다.",
  "How far from the mouse a unit still counts, in map pixels (32 a tile); farther, and the pick finds nothing.": "마우스에서 얼마나 떨어진 유닛까지 셀지 맵 픽셀로 정합니다 (타일당 32). 더 멀면 아무것도 고르지 않습니다.",
  "How many bits of the counter to carry: 16 is half the triggers for a counter that stays under 65536": "카운터의 몇 비트를 옮길지 정합니다. 65536 미만으로 유지되는 카운터라면 16비트로 트리거가 절반이 됩니다",
  "How many times the upgrade can be researched. Writing it did nothing in Remastered (probe 8: Infantry Armor still stopped at 3), so it is a read only.": "업그레이드를 몇 번 연구할 수 있는지입니다. Remastered에서는 써도 아무 일이 없었으므로 (probe 8: 보병 방어력이 여전히 3에서 멈춤) 읽기 전용입니다.",
  "HP": "HP",
  "in a transport": "수송선 안",
  "In frames. Verified (probe 9).": "프레임 단위. 확인됨 (probe 9).",
  "In pixels, 32 a tile. Verified: marines could not shoot a zergling up close (probe 9).": "픽셀 단위, 타일당 32. 확인됨: 마린이 가까이 붙은 저글링을 쏘지 못했습니다 (probe 9).",
  "In pixels, 32 a tile. Verified: marines shot from farther (probe 8).": "픽셀 단위, 타일당 32. 확인됨: 마린이 더 먼 곳에서 쐈습니다 (probe 8).",
  "In plain words": "쉬운 말로",
  "In tiles, up to 11. Verified: a marine with sight 1 revealed only a tiny circle (probe 9). A beacon reveals around itself, so stand clear of one to see it.": "타일 단위, 11까지. 확인됨: 시야 1인 마린은 아주 작은 원만 밝혔습니다 (probe 9). 비컨은 주변을 밝히므로 비컨에서 떨어져서 확인하세요.",
  "independent": "독립형",
  "Inertia": "관성",
  "Invincibility of a placed unit": "배치된 유닛의 무적",
  "Invincibility of placed unit {index} is {value}": "배치된 유닛 {index}의 무적: {value}",
  "invincible": "무적",
  "Invincible flag of a unit type": "유닛 종류의 무적 플래그",
  "irradiate": "이레디에이트",
  "is": "예",
  "is not": "아니요",
  "is still in the game": "아직 게임에 있음",
  "It does nothing when it fires.": "실행되어도 아무것도 하지 않습니다.",
  "It fires on the first cycle.": "첫 주기에 실행됩니다.",
  "It fires once and then stops.": "한 번 실행되고 멈춥니다.",
  "It fires once for each owner and then stops.": "소유자마다 한 번 실행되고 멈춥니다.",
  "It is preserved, so it fires again on every cycle ({clock}) its conditions hold.": "보존되므로 조건이 맞는 주기({clock})마다 다시 실행됩니다.",
  "It is preserved, so it runs again every cycle ({clock}).": "보존되므로 매 주기({clock}) 다시 실행됩니다.",
  "It needs a free counter unit and a free location slot.": "빈 카운터 유닛과 빈 로케이션 슬롯이 필요합니다.",
  "It needs a free counter unit and, for the mouse, nine free location slots.": "빈 카운터 유닛이 필요하고, 마우스에는 빈 로케이션 슬롯 9개가 더 필요합니다.",
  "It needs nine free location slots for MSQC.": "MSQC용 빈 로케이션 슬롯이 9개 필요합니다.",
  "It writes {n} records and the trigger has {free} action slots left.": "이 행은 레코드 {n}개를 쓰는데 트리거에 남은 액션 칸은 {free}개입니다.",
  "Its Magenta data could not be read. Start over from the notice at the top of the panel, or update Magenta.": "이 맵의 Magenta 데이터를 읽을 수 없습니다. 패널 위의 알림에서 새로 시작하거나 Magenta를 업데이트하세요.",
  "its size": "원래 크기",
  "Key": "키",
  "key 0x{hex}": "키 0x{hex}",
  "Keyboard key state": "키보드 키 상태",
  "kill": "죽이기",
  "Kill all {Unit} owned by {Player}": "{Player}의 {Unit} 모두 죽임",
  "Kill everything at {location}": "{location}의 모든 것 죽이기",
  "Kill {Count} {Unit} owned by {Player} at {Location}": "{Location}에 있는 {Player}의 {Unit} {Count} 죽임",
  "kills": "처치 수",
  "Kills": "처치",
  "Kills and razings": "처치와 파괴",
  "Label": "제목",
  "large": "대형",
  "last {n} of {total}": "{total}개 중 마지막 {n}개",
  "left": "왼쪽",
  "less than": "미만",
  "levels": "단계",
  "Lift the sprite and image limits": "스프라이트와 이미지 개수 제한 해제",
  "Load {Scenario} after this scenario": "이 시나리오 다음에 {Scenario} 불러오기",
  "Local player": "로컬 플레이어",
  "Local to each computer, like the local player.": "로컬 플레이어처럼 컴퓨터마다 따로입니다.",
  "Local to each computer. Center View moves it natively.": "컴퓨터마다 따로입니다. Center View가 기본 방법으로 옮깁니다.",
  "Local to each computer. Needs triggers running every frame to catch a press. Verified in Remastered 2026-09-12: the press reads as 1 for a frame and the key reads 0 again at once, even while held; 2 and 3 never appeared.": "컴퓨터마다 따로입니다. 누름을 잡으려면 트리거가 매 프레임 실행되어야 합니다. 2026-09-12 Remastered에서 확인: 누르면 한 프레임 동안 1로 읽히고, 누르고 있어도 바로 다시 0으로 읽힙니다. 2와 3은 나타나지 않았습니다.",
  "Location": "로케이션",
  "location {n}": "로케이션 {n}",
  "lockdown": "락다운",
  "Log": "기록",
  "Looks of a unit type": "유닛 종류의 모습",
  "Loop a sound as background music": "사운드를 배경 음악으로 반복 재생",
  "loses": "패배",
  "lost": "패배",
  "maelstrom": "마엘스트롬",
  "Magenta cannot change this map yet": "Magenta가 아직 이 맵을 바꿀 수 없습니다",
  "Magenta needs it to build this map.": "Magenta가 이 맵을 빌드하는 데 필요합니다.",
  "Magenta Settings": "Magenta 설정",
  "Magenta's counter add": "Magenta의 카운터 더하기",
  "Magenta's counter comparison": "Magenta의 카운터 비교",
  "Magenta's counter copy": "Magenta의 카운터 복사",
  "Magenta's counter subtract": "Magenta의 카운터 빼기",
  "Magenta's per-player copies": "Magenta의 플레이어별 복사본",
  "Magenta: describe a trigger": "Magenta: 트리거 설명",
  "Magenta: dry run": "Magenta: 모의 실행",
  "Magenta…": "Magenta…",
  "make invincible": "무적으로",
  "make vulnerable": "무적 해제",
  "Make {unit} look like {value}": "{unit}의 모습 설정: {value}",
  "Make {unit} {value}": "{unit} 설정: {value}",
  "Map revision": "맵 버전",
  "Map-wide": "맵 전체",
  "Max hit points of a unit type": "유닛 종류의 최대 체력",
  "Max shields of a unit type": "유닛 종류의 최대 보호막",
  "Max speed": "최고 속도",
  "Maximum level of an upgrade": "업그레이드의 최대 단계",
  "mechanical": "기계",
  "Mechanical flag of a unit type": "유닛 종류의 기계 플래그",
  "medium": "중형",
  "memory 0x{hex} = {value}": "메모리 0x{hex} = {value}",
  "Memory address…": "메모리 주소…",
  "memory at 0x{addr}": "메모리 0x{addr}",
  "Message at the start": "시작할 때 메시지",
  "middle": "가운데",
  "Milliseconds": "밀리초",
  "Mineral cost of a technology": "기술의 미네랄 비용",
  "Mineral cost of a unit type": "유닛 종류의 미네랄 비용",
  "Mineral cost of an upgrade": "업그레이드의 미네랄 비용",
  "minerals": "미네랄",
  "Minerals for each kill": "처치할 때마다 미네랄",
  "Minerals of a player": "플레이어의 미네랄",
  "Minimum range of a weapon": "무기의 최소 사거리",
  "missing": "없음",
  "Mission briefing": "임무 브리핑",
  "Modifier": "변경 방식",
  "modulo": "나머지",
  "More": "더 보기",
  "Mouse X on screen": "화면 위 마우스 X",
  "Mouse Y on screen": "화면 위 마우스 Y",
  "move": "이동",
  "Move": "옮길 로케이션",
  "move a location\u0004by": "만큼",
  "move a location\u0004to": "좌표로",
  "Move a location to coordinates or by an offset": "로케이션을 좌표로 또는 만큼 옮기기",
  "Move action": "액션 이동",
  "Move condition": "조건 이동",
  "Move down (Alt+Down)": "아래로 이동 (Alt+Down)",
  "Move trigger": "트리거 이동",
  "Move up (Alt+Up)": "위로 이동 (Alt+Up)",
  "Move {Count} {Unit} owned by {Player} from {From} to {To}": "{From}에 있는 {Player}의 {Unit} {Count|을} {To|으로} 옮김",
  "Move {location} {mode} {x}, {y}": "{location} 이동({mode}): {x}, {y}",
  "Move {location} {mode} {x}, {y} keeping {size}": "{location} 이동({mode}): {x}, {y}, 크기 {size}",
  "moved and used by": "옮기고 쓰는 트리거:",
  "moved by": "옮기는 트리거:",
  "moving": "이동 중",
  "Multiply, divide or randomize a counter": "카운터 곱하기, 나누기, 무작위",
  "Mute unit speech": "유닛 음성 끄기",
  "Name counter": "카운터 이름 붙이기",
  "Name for switch {n}": "스위치 {n}의 이름",
  "Name for the new counter": "새 카운터의 이름",
  "Name for this death counter": "이 데스 카운터의 이름",
  "Name of a unit type": "유닛 종류의 이름",
  "Name switch {name}": "스위치 이름 {name}",
  "Name {unit} {value}": "{unit}의 이름 설정: {value}",
  "Named counters": "이름 있는 카운터",
  "name…": "이름…",
  "nearest to": "가장 가까운",
  "Needs a build": "빌드 필요",
  "Needs a Build (⋯ menu). The MSQC plugin in the built map turns each player's input into a game command, so every computer sees the same press in the same cycle, before its triggers run; the cell is cleared once they have.": "빌드 필요 (⋯ 메뉴). 빌드한 맵의 MSQC 플러그인이 각 플레이어의 입력을 게임 명령으로 바꾸므로, 모든 컴퓨터가 같은 주기에 트리거가 실행되기 전에 같은 입력을 봅니다. 트리거가 실행되고 나면 칸이 비워집니다.",
  "Needs a Build (⋯ menu): the built map checks this every cycle, before the triggers run, and leaves the answer in a cell this condition reads.": "빌드 필요 (⋯ 메뉴): 빌드한 맵이 매 주기 트리거가 실행되기 전에 이것을 검사하고, 이 조건이 읽는 칸에 답을 남깁니다.",
  "Needs a Build (⋯ menu): the chat plugin in the built map writes the command's number into a cell this condition reads, in the cycle the message arrives, for every player at once. A message with a number is matched as a pattern and the number is parsed out for you.": "빌드 필요 (⋯ 메뉴): 빌드한 맵의 채팅 플러그인이 메시지가 도착한 주기에 명령 번호를 이 조건이 읽는 칸에 모든 플레이어에게 한꺼번에 씁니다. 숫자가 붙은 메시지는 패턴으로 맞추고 숫자를 따로 읽어 줍니다.",
  "Needs a Build (⋯ menu): the game's own triggers cannot do this, so the built map carries the code that does. It runs once every trigger has had its turn this cycle — a row below it in this trigger still sees the map as it was; a trigger in the next cycle sees the result. The source map stays as it is.": "빌드 필요 (⋯ 메뉴): 게임의 트리거로는 할 수 없는 일이라 빌드한 맵에 그 일을 하는 코드가 들어갑니다. 이번 주기에 모든 트리거가 한 차례씩 실행된 뒤에 실행되므로, 이 트리거에서 아래에 있는 행은 아직 이전 상태의 맵을 보고, 다음 주기의 트리거가 결과를 봅니다. 원본 맵은 그대로입니다.",
  "Needs a Build to work in the game": "게임에서 동작하려면 빌드가 필요합니다",
  "Needs a location under the unit": "유닛 아래에 로케이션이 있어야 합니다",
  "neutral": "중립",
  "Never": "절대 안 함",
  "Never above the type's maximum.": "유닛 종류의 최대치를 넘지 않습니다.",
  "Never below 0; a unit whose hit points reach 0 dies.": "0 밑으로는 내려가지 않습니다. 체력이 0이 된 유닛은 죽습니다.",
  "New": "새로 만들기",
  "New counter": "새 카운터",
  "New counter…": "새 카운터…",
  "New folder": "새 폴더",
  "New folder…": "새 폴더…",
  "New trigger": "새 트리거",
  "New trigger about this {unit}…": "이 {unit}에 대한 새 트리거…",
  "New trigger at {location}…": "{location}에서 새 트리거…",
  "New trigger from the map": "맵에서 새 트리거",
  "No active player runs this trigger, so it cannot fire.": "이 트리거를 실행하는 활성 플레이어가 없어 실행될 수 없습니다.",
  "No build rows": "빌드 행 없음",
  "No chat commands": "채팅 명령 없음",
  "No conditions: it fires on the first cycle.": "조건 없음: 첫 주기에 실행됩니다.",
  "no counter": "카운터 없음",
  "No counter": "카운터 없음",
  "No counter has a name yet. Name one from a Deaths row's name… chip, or from a counter chip's New counter…": "아직 이름 있는 카운터가 없습니다. Deaths 행의 이름… 칩이나 카운터 칩의 새 카운터…에서 이름을 붙이세요.",
  "No free counter cell": "빈 카운터 칸이 없습니다",
  "No free counter cell for the build row": "빌드 행에 쓸 빈 카운터 칸이 없습니다",
  "No free counter cell for the chat command": "채팅 명령에 쓸 빈 카운터 칸이 없습니다",
  "No free counter cell for the check": "검사에 쓸 빈 카운터 칸이 없습니다",
  "No free counter cell for the copy's build rows": "복사본의 빌드 행에 쓸 빈 카운터 칸이 없습니다",
  "No free counter cells for a chat pattern": "채팅 패턴에 쓸 빈 카운터 칸이 없습니다",
  "No free counter cells for the comparison": "비교에 쓸 빈 카운터 칸이 없습니다",
  "No free counter cells for the number": "숫자에 쓸 빈 카운터 칸이 없습니다",
  "No free counter cells for the step": "단계에 쓸 빈 카운터 칸이 없습니다",
  "No free location slot": "빈 로케이션 슬롯 없음",
  "no location": "로케이션 없음",
  "No location": "로케이션 없음",
  "No map is open.": "열린 맵이 없습니다.",
  "No other trigger uses the switches, counters or locations this one touches.": "이 트리거가 다루는 스위치, 카운터, 로케이션을 쓰는 다른 트리거가 없습니다.",
  "No player owns this trigger, so it never runs.": "이 트리거를 소유한 플레이어가 없어서 실행되지 않습니다.",
  "no properties": "속성 없음",
  "No room for synced input": "동기화 입력을 넣을 공간이 없습니다",
  "No room for the mouse": "마우스용 공간 없음",
  "No room for this row": "이 행을 넣을 공간이 없습니다",
  "No sound": "사운드 없음",
  "no sound": "사운드 없음",
  "No synced input": "동기화 입력 없음",
  "No triggers.": "트리거가 없습니다.",
  "no version": "버전 없음",
  "no weapon": "무기 없음",
  "No weapon": "무기 없음",
  "Normal": "보통",
  "not a detector": "탐지기 아님",
  "not a hero": "영웅 아님",
  "not built": "빌드 안 됨",
  "Not built: the build runtime was not installed.": "빌드하지 않았습니다. 빌드 런타임이 설치되지 않았습니다.",
  "not invincible": "무적 아님",
  "not mechanical": "기계 아님",
  "not organic": "생체 아님",
  "not permanently cloaked": "영구 은폐 아님",
  "not regenerating hit points": "체력 재생 안 함",
  "not researched": "연구 안 됨",
  "not robotic": "로봇 아님",
  "not set": "설정 안 됨",
  "Not yet seen working in Remastered.": "아직 Remastered에서 동작을 확인하지 않았습니다.",
  "Nothing has happened yet. Step runs one cycle.": "아직 아무 일도 없습니다. 한 단계는 주기 하나를 실행합니다.",
  "Nothing in this map needs a build; a plain save is all it takes.": "이 맵에는 빌드가 필요한 것이 없습니다. 그냥 저장하면 됩니다.",
  "Nothing matches.": "맞는 것이 없습니다.",
  "objectives:": "임무 목표:",
  "off": "끔",
  "OK": "확인",
  "on": "켬",
  "One comparison per trigger": "트리거마다 비교는 하나만",
  "One copy of this trigger per player ticked, owned by that player, with the group below replaced by the player in every condition and action. This trigger becomes the template and stops running itself.": "체크한 플레이어마다 그 플레이어가 소유한 이 트리거의 복사본을 하나씩 만들고, 모든 조건과 액션에서 아래 그룹을 그 플레이어로 바꿉니다. 이 트리거는 틀이 되어 직접 실행되지 않습니다.",
  "One line.": "한 줄만 쓸 수 있습니다.",
  "One Marine for Player 1 at the start; change the unit, the count and the player": "시작할 때 Player 1에게 마린 1기. 유닛, 수, 플레이어를 바꾸세요",
  "One message to everyone when the game begins. Change the text.": "게임이 시작되면 모두에게 메시지를 하나 보냅니다. 텍스트를 바꾸세요.",
  "Only StarCraft: Remastered runs this row; the map is marked {revision}, a revision 1.16.1 also plays.": "이 행은 StarCraft: Remastered에서만 실행됩니다. 맵은 1.16.1에서도 열리는 {revision}(으)로 표시되어 있습니다.",
  "open": "열림",
  "Open a map first": "먼저 맵을 여세요",
  "Open Magenta": "Magenta 열기",
  "Open {plugin}": "{plugin} 열기",
  "orange": "주황",
  "Order": "명령",
  "order id": "명령 번호",
  "order to attack-move to": "공격 이동 명령:",
  "order to move to": "이동 명령:",
  "order to patrol to": "정찰 명령:",
  "Order {Unit} owned by {Player} at {From} to {Order} to {To}": "{From}에 있는 {Player}의 {Unit}에게 {To|으로} {Order} 명령",
  "Ordering one unit at a time needs a location of Magenta's own; free a location slot first.": "유닛마다 따로 명령하려면 Magenta 전용 로케이션이 필요합니다. 먼저 로케이션 슬롯을 하나 비우세요.",
  "ore": "미네랄",
  "ore and gas": "미네랄과 가스",
  "organic": "생체",
  "Organic flag of a unit type": "유닛 종류의 생체 플래그",
  "other": "기타",
  "owner": "소유자",
  "Owner of a placed unit": "배치된 유닛의 소유자",
  "Panel": "패널",
  "Paste triggers": "트리거 붙여넣기",
  "Paste triggers from text": "텍스트에서 트리거 붙여넣기",
  "patrol": "정찰",
  "Pause the countdown timer": "카운트다운 타이머 일시 정지",
  "Pause the game": "게임 일시 정지",
  "Percent": "퍼센트",
  "Permanent cloak flag of a unit type": "유닛 종류의 영구 은폐 플래그",
  "permanently cloaked": "영구 은폐",
  "Pick a trigger in the Magenta panel to see its conditions decided here.": "Magenta 패널에서 트리거를 고르면 여기서 조건의 결과를 볼 수 있습니다.",
  "Pick a trigger on the left, or add one.": "왼쪽에서 트리거를 고르거나 새로 추가하세요.",
  "Pick near the mouse": "마우스 근처에서 고르기",
  "Pick on map": "맵에서 고르기",
  "Ping the minimap at {Location}": "미니맵의 {Location}에 핑",
  "pixels": "픽셀",
  "Placed unit": "배치된 유닛",
  "Placed unit slot {n}: the game fills the slots in map order, so the number stays right while no unit is added before it": "배치된 유닛 슬롯 {n}: 게임은 맵 순서대로 슬롯을 채우므로, 앞에 유닛을 추가하지 않는 한 번호가 맞습니다",
  "Placed unit {index} is {value}": "배치된 유닛 {index}의 종류: {value}",
  "Placed units": "배치된 유닛",
  "plague": "플레이그",
  "Play {WAV} ({Duration} ms)": "{WAV} 재생 ({Duration}ms)",
  "Player": "플레이어",
  "Player 2's row with Player 1's bit on lets Player 1 see what Player 2 sees: the row is whose sight is shared, the bit who receives it (probe 9).": "Player 2의 행에서 Player 1의 비트를 켜면 Player 1이 Player 2가 보는 것을 봅니다. 행은 시야를 주는 쪽, 비트는 받는 쪽입니다 (probe 9).",
  "Players": "플레이어",
  "Portrait slot, 1 to 4": "초상화 슬롯, 1–4",
  "Preserve trigger": "트리거 보존",
  "pressed": "눌림",
  "Pressing M gives the player who pressed it 100 minerals. A synced key press: every computer sees it, so the game stays in step. Needs a Build. Change the key.": "M을 누른 플레이어가 미네랄 100을 받습니다. 동기화된 키 입력이라 모든 컴퓨터가 함께 보므로 게임이 어긋나지 않습니다. 빌드가 필요합니다. 키를 바꾸세요.",
  "Properties": "속성",
  "properties slot {n}": "속성 슬롯 {n}",
  "Protoss": "프로토스",
  "purple": "보라",
  "Put a second comparison in another trigger.": "두 번째 비교는 다른 트리거에 넣으세요.",
  "Put units": "유닛 놓기",
  "px high": "px 높이",
  "px wide": "px 너비",
  "px/frame": "px/프레임",
  "Race": "종족",
  "Race of a player": "플레이어의 종족",
  "random": "무작위",
  "randomize": "무작위",
  "Range of a weapon": "무기의 사거리",
  "Razings": "파괴",
  "Read a unit's stat into a counter": "유닛 능력치를 카운터로 읽기",
  "read and write": "읽기와 쓰기",
  "read by": "읽는 트리거:",
  "read only": "읽기 전용",
  "Reads memory at 0x{hex}, which the catalogue does not know.": "카탈로그에 없는 메모리 0x{hex}을(를) 읽습니다.",
  "ready in this editor": "이 편집기에 준비됨",
  "Recipes…": "레시피…",
  "Recipe…": "레시피…",
  "red": "빨강",
  "Redo {what}": "다시 실행: {what}",
  "regenerating hit points": "체력 재생",
  "Regeneration flag of a unit type": "유닛 종류의 재생 플래그",
  "Reinforcements every minute": "1분마다 증원",
  "released (not seen in the game)": "뗌 (게임에서 확인 안 됨)",
  "remaining build time": "남은 생산 시간",
  "Remastered does not let a trigger write this address; the action does nothing in the game.": "Remastered에서는 트리거가 이 주소에 쓸 수 없습니다. 게임에서 이 액션은 아무 일도 하지 않습니다.",
  "Remastered does not let a trigger write {what}.": "Remastered에서는 트리거가 {what}을(를) 쓸 수 없습니다.",
  "remove": "제거",
  "Remove": "제거",
  "Remove (Delete)": "제거 (Delete)",
  "Remove action": "액션 제거",
  "Remove all {Unit} owned by {Player}": "{Player}의 {Unit} 모두 제거",
  "Remove build row": "빌드 행 제거",
  "Remove comparison": "비교 제거",
  "Remove condition": "조건 제거",
  "Remove counter step": "카운터 단계 제거",
  "Remove folder": "폴더 제거",
  "Remove folder (keep triggers)": "폴더 제거 (트리거는 유지)",
  "Remove {Count} {Unit} owned by {Player} at {Location}": "{Location}에 있는 {Player}의 {Unit} {Count} 제거",
  "Rename folder": "폴더 이름 바꾸기",
  "Rename switch": "스위치 이름 바꾸기",
  "Rename trigger": "트리거 이름 바꾸기",
  "Rename…": "이름 바꾸기…",
  "rescuable": "구조 가능",
  "Research time of a technology": "기술의 연구 시간",
  "Research time of an upgrade": "업그레이드의 연구 시간",
  "researched": "연구됨",
  "Reset": "초기화",
  "Resource": "자원",
  "resources": "자원",
  "Respawn a unit when it dies": "유닛이 죽으면 다시 생성",
  "right": "오른쪽",
  "robotic": "로봇",
  "Robotic flag of a unit type": "유닛 종류의 로봇 플래그",
  "Row {row} moves {location} only after this cycle's triggers have all run, so this row still sees it where it was. Put this row in a trigger that fires in a later cycle.": "{row}번 행은 이번 주기의 트리거가 모두 실행된 뒤에야 {location}을(를) 옮기므로, 이 행은 아직 원래 자리의 로케이션을 봅니다. 이 행을 다음 주기에 실행되는 트리거로 옮기세요.",
  "Run 10": "10번 실행",
  "Run for each player": "플레이어별로 실행",
  "Run on": "계속 실행",
  "Run one trigger cycle": "트리거 주기 한 번 실행",
  "Run the AI script {Script}": "AI 스크립트 {Script} 실행",
  "Run the AI script {Script} at {Location}": "{Location}에서 AI 스크립트 {Script} 실행",
  "Run this trigger for each player…": "이 트리거를 플레이어별로 실행…",
  "Run triggers every frame": "트리거 매 프레임 실행",
  "Run triggers every two seconds": "트리거 2초마다 실행",
  "Runs for": "실행 대상",
  "Runs once for each of": "각각 한 번씩 실행:",
  "Runs once for each of {players}, with {group} standing for the player in every condition and action.": "{players} 각각에 대해 한 번씩 실행되며, 모든 조건과 액션에서 {group}이(가) 그 플레이어를 뜻합니다.",
  "s": "초",
  "Scenario": "시나리오",
  "Score": "점수",
  "Screen X on the map": "맵 위 화면 X",
  "Screen Y on the map": "맵 위 화면 Y",
  "Script": "스크립트",
  "Search triggers…": "트리거 검색…",
  "Seconds": "초",
  "seconds": "초",
  "Seconds at the fastest speed; the game counts these timers in ticks of about eight frames. The effect applies without the spell's overlay graphic.": "가장 빠른 속도 기준 초입니다. 게임은 이 타이머를 약 8프레임 단위로 셉니다. 효과는 마법 그래픽 없이 적용됩니다.",
  "Seconds on the game clock": "게임 시계의 초",
  "Seen by": "받는 쪽",
  "Seen working in Remastered.": "Remastered에서 동작을 확인했습니다.",
  "Selected trigger": "선택한 트리거",
  "set": "설정",
  "Set a counter": "카운터 설정",
  "Set a switch": "스위치 켜기",
  "set and read by": "설정하고 읽는 트리거:",
  "set by": "설정하는 트리거:",
  "Set deaths of {Unit} for {Player} {Modifier} {Amount}": "{Player}의 {Unit} 데스 {Modifier} {Amount}",
  "set energy": "에너지 설정",
  "set hit points": "체력 설정",
  "Set invincibility of placed unit {index} to {value}": "배치된 유닛 {index}의 무적 설정: {value}",
  "set kills": "처치 수 설정",
  "Set once a human leaves. Not yet seen working in Remastered.": "사람 플레이어가 나가면 설정됩니다. 아직 Remastered에서 동작을 확인하지 않았습니다.",
  "Set revision to Remastered": "버전을 Remastered로 설정",
  "set shields": "보호막 설정",
  "Set the air weapon of {unit} to {value}": "{unit}의 공중 무기 설정: {value}",
  "Set the armor of {unit} {mod} {value}": "{unit}의 방어력 {mod} {value}",
  "Set the build time of {unit} {mod} {value}": "{unit}의 생산 시간 {mod} {value}",
  "Set the colour of {player} to {value}": "{player}의 색 설정: {value}",
  "Set the cooldown of {weapon} {mod} {value}": "{weapon}의 재사용 대기시간 {mod} {value}",
  "Set the countdown timer {Modifier} {Seconds} seconds": "카운트다운 타이머 {Modifier} {Seconds}초",
  "Set the damage bonus per upgrade of {weapon} {mod} {value}": "{weapon}의 업그레이드당 추가 공격력 {mod} {value}",
  "Set the damage factor of {weapon} {mod} {value}": "{weapon}의 공격 횟수 {mod} {value}",
  "Set the damage of {weapon} {mod} {value}": "{weapon}의 공격력 {mod} {value}",
  "Set the energy cost of {tech} {mod} {value}": "{tech}의 에너지 비용 {mod} {value}",
  "Set the energy of placed unit {index} {mod} {value}": "배치된 유닛 {index}의 에너지 {mod} {value}",
  "Set the energy of {Count} {Unit} owned by {Player} at {Location} to {Percent}%": "{Location}에 있는 {Player}의 {Unit} {Count}의 에너지를 {Percent}%로 설정",
  "Set the gas cost of {tech} {mod} {value}": "{tech}의 가스 비용 {mod} {value}",
  "Set the gas cost of {unit} {mod} {value}": "{unit}의 가스 비용 {mod} {value}",
  "Set the gas cost of {upgrade} {mod} {value}": "{upgrade}의 가스 비용 {mod} {value}",
  "Set the gas of {player} {mod} {value}": "{player}의 가스 {mod} {value}",
  "Set the ground weapon of {unit} to {value}": "{unit}의 지상 무기 설정: {value}",
  "Set the hallucination flag of placed unit {index} to {value}": "배치된 유닛 {index}의 환영 플래그 설정: {value}",
  "Set the hit points of placed unit {index} {mod} {value}": "배치된 유닛 {index}의 체력 {mod} {value}",
  "Set the hit points of {Count} {Unit} owned by {Player} at {Location} to {Percent}%": "{Location}에 있는 {Player}의 {Unit} {Count}의 체력을 {Percent}%로 설정",
  "Set the level of {upgrade} for {player} {mod} {value}": "{player}의 {upgrade} 단계 {mod} {value}",
  "Set the max hit points of {unit} {mod} {value}": "{unit}의 최대 체력 {mod} {value}",
  "Set the max shields of {unit} {mod} {value}": "{unit}의 최대 보호막 {mod} {value}",
  "Set the mineral cost of {tech} {mod} {value}": "{tech}의 미네랄 비용 {mod} {value}",
  "Set the mineral cost of {unit} {mod} {value}": "{unit}의 미네랄 비용 {mod} {value}",
  "Set the mineral cost of {upgrade} {mod} {value}": "{upgrade}의 미네랄 비용 {mod} {value}",
  "Set the minerals of {player} {mod} {value}": "{player}의 미네랄 {mod} {value}",
  "Set the minimum range of {weapon} {mod} {value}": "{weapon}의 최소 사거리 {mod} {value}",
  "Set the mission objectives to {Text}": "임무 목표 설정: {Text}",
  "Set the owner of placed unit {index} to {value}": "배치된 유닛 {index}의 소유자 설정: {value}",
  "Set the range of {weapon} {mod} {value}": "{weapon}의 사거리 {mod} {value}",
  "set the rank": "계급 설정",
  "set the remaining build time": "남은 생산 시간 설정",
  "Set the research time of {tech} {mod} {value}": "{tech}의 연구 시간 {mod} {value}",
  "Set the research time of {upgrade} {mod} {value}": "{upgrade}의 연구 시간 {mod} {value}",
  "set the resources": "자원 설정",
  "Set the resources of {Count} resource units owned by {Player} at {Location} to {Amount}": "{Location}에 있는 {Player}의 자원 유닛 {Count}의 자원을 {Amount|으로} 설정",
  "Set the revision to Remastered 1.21+ and older clients refuse the map instead of playing it without these rows.": "버전을 Remastered 1.21+로 설정하면 예전 클라이언트는 이 행들 없이 맵을 실행하는 대신 맵을 열지 않습니다.",
  "Set the shields of placed unit {index} {mod} {value}": "배치된 유닛 {index}의 보호막 {mod} {value}",
  "Set the shields of {Count} {Unit} owned by {Player} at {Location} to {Percent}%": "{Location}에 있는 {Player}의 {Unit} {Count}의 보호막을 {Percent}%로 설정",
  "Set the sight range of {unit} {mod} {value}": "{unit}의 시야 {mod} {value}",
  "Set the size of {unit} to {value}": "{unit}의 크기 설정: {value}",
  "Set the speed of {unit} to {value}": "{unit}의 속도 설정: {value}",
  "Set the stance of {player} toward {other} to {value}": "{other}에 대한 {player}의 관계 설정: {value}",
  "Set the supply provided by {unit} {mod} {value}": "{unit}이(가) 주는 보급 {mod} {value}",
  "Set the supply used by {unit} {mod} {value}": "{unit}이(가) 쓰는 보급 {mod} {value}",
  "Set the target acquisition range of {unit} {mod} {value}": "{unit}의 대상 탐색 범위 {mod} {value}",
  "Set the trigger timer {mod} {value}": "트리거 타이머 {mod} {value}",
  "Set the {race} supply cap of {player} {mod} {value}": "{player}의 {race} 보급 한도 {mod} {value}",
  "Set the {race} supply provided to {player} {mod} {value}": "{player}의 {race} 보급 제공량 {mod} {value}",
  "Set the {race} supply used by {player} {mod} {value}": "{player}의 {race} 보급 사용량 {mod} {value}",
  "Set the {Score} score of {Player} {Modifier} {Amount}": "{Player}의 {Score} 점수 {Modifier} {Amount}",
  "Set this {unit}'s hit points (EUD)": "이 {unit}의 체력 설정 (EUD)",
  "Set To": "설정",
  "Set to 0 every cycle by the every-frame switch; every probe map runs on it.": "매 프레임 실행 스위치가 매 주기 0으로 설정합니다. 모든 probe 맵이 이것으로 실행됩니다.",
  "Set vision of {player} for {other} to {value}": "{player}의 시야를 {other}에게 공유: {value}",
  "Set {counter} to the number of {units}": "{counter} 설정: {units}의 수",
  "Set {counter} to the {field} of the first {units}": "{counter} 설정: 첫 번째 {units}의 {field}",
  "Set {counter} to {a} {op} {b}": "{counter} 설정: {a} {op} {b}",
  "Set {counter} to {op} {b}": "{counter} 설정: {op} {b}",
  "Set {counter} {mod} {amount}": "{counter} {mod} {amount}",
  "Set {Player} to {Status}": "{Player|을} {Status|으로} 설정",
  "Set {Resource} of {Player} {Modifier} {Amount}": "{Player}의 {Resource} {Modifier} {Amount}",
  "Set {tech} for {player} to {value}": "{player}의 {tech} 설정: {value}",
  "Settings…": "설정…",
  "Shared vision between players": "플레이어 사이의 시야 공유",
  "shields": "보호막",
  "shields %": "보호막 %",
  "Shields of a placed unit": "배치된 유닛의 보호막",
  "Show": "보기",
  "Show a leader board of most {Resource}, labelled {Label}": "리더보드 표시: {Resource}, 제목 {Label}",
  "Show a leader board of most {Score} points, labelled {Label}": "리더보드 표시: {Score} 점수, 제목 {Label}",
  "Show a leader board of most {Unit} controlled at {Location}, labelled {Label}": "리더보드 표시: {Location}의 {Unit} 보유 수, 제목 {Label}",
  "Show a leader board of most {Unit} controlled, labelled {Label}": "리더보드 표시: {Unit} 보유 수, 제목 {Label}",
  "Show a leader board of most {Unit} killed, labelled {Label}": "리더보드 표시: {Unit} 처치 수, 제목 {Label}",
  "Show a leader board of {Resource} with a goal of {Goal}, labelled {Label}": "리더보드 표시: {Resource}, 목표 {Goal}, 제목 {Label}",
  "Show a leader board of {Score} points with a goal of {Goal}, labelled {Label}": "리더보드 표시: {Score} 점수, 목표 {Goal}, 제목 {Label}",
  "Show a leader board of {Unit} controlled at {Location} with a goal of {Goal}, labelled {Label}": "리더보드 표시: {Location}의 {Unit} 보유 수, 목표 {Goal}, 제목 {Label}",
  "Show a leader board of {Unit} controlled with a goal of {Goal}, labelled {Label}": "리더보드 표시: {Unit} 보유 수, 목표 {Goal}, 제목 {Label}",
  "Show a leader board of {Unit} killed with a goal of {Goal}, labelled {Label}": "리더보드 표시: {Unit} 처치 수, 목표 {Goal}, 제목 {Label}",
  "Show as player and unit": "플레이어와 유닛으로 보기",
  "Show every trigger": "모든 트리거 보기",
  "Show only EUD triggers": "EUD 트리거만 보기",
  "Show only triggers with a problem": "문제가 있는 트리거만 보기",
  "Show or hide the trigger list": "트리거 목록 보이기/숨기기",
  "Show text with numbers in it": "숫자가 들어간 텍스트 표시",
  "Show the greed leader board with a goal of {Goal} resources": "탐욕 리더보드 표시: 목표 자원 {Goal}",
  "Show the portrait of {Unit} in {Slot}": "{Slot}에 {Unit} 초상화 표시",
  "Show the talking portrait of {Unit} for {Duration} ms": "{Unit}의 말하는 초상화를 {Duration}ms 동안 표시",
  "Show {Text} for {Duration} ms": "{Duration}ms 동안 표시: {Text}",
  "Show {text} to {player}": "{player}에게 {text} 표시",
  "Sight range of a unit type": "유닛 종류의 시야",
  "Size of a unit type": "유닛 종류의 크기",
  "Slot": "슬롯",
  "Slot of a player": "플레이어의 슬롯",
  "Slot order as for hit points: not simply map order, being probed. Slots: the first placed unit is slot 0 and later ones count down from 1699 (verified in Remastered 2026-09-12); the chip picks a unit on the map and works the slot out. Start locations take no slot; nor does a unit of a human player who is not in the game (it is removed at load), so slots after one shift by one when that player is missing.": "슬롯 순서는 체력과 같습니다. 단순한 맵 순서가 아니며 확인 중입니다. 슬롯: 처음 배치된 유닛이 슬롯 0이고 그 뒤로는 1699부터 거꾸로 셉니다 (2026-09-12 Remastered에서 확인). 칩에서 맵의 유닛을 고르면 슬롯을 계산해 줍니다. 시작 위치는 슬롯을 차지하지 않고, 게임에 없는 사람 플레이어의 유닛도 불러올 때 지워지므로 차지하지 않습니다. 그래서 그 플레이어가 없으면 뒤의 슬롯이 하나씩 밀립니다.",
  "slot {n}": "슬롯 {n}",
  "Slow": "느림",
  "Slower": "더 느림",
  "Slowest": "가장 느림",
  "small": "소형",
  "Sound": "사운드",
  "sound {n}": "사운드 {n}",
  "Source: {source}.": "출처: {source}.",
  "Speed of a unit type": "유닛 종류의 속도",
  "stale": "오래됨",
  "Stands for the player": "플레이어를 뜻하는 그룹",
  "Start following at once (a trigger sets the cammove switch)": "바로 따라가기 시작 (트리거가 cammove 스위치를 켬)",
  "Start from a whole trigger: a beacon shop, a countdown, a respawn…": "완성된 트리거로 시작합니다: 비컨 상점, 카운트다운, 부활…",
  "Start from…": "시작할 트리거…",
  "Start over from the map as it is now": "지금의 맵에서 다시 시작",
  "Start the camera": "카메라 시작",
  "stasis": "스테이시스",
  "State": "상태",
  "Status": "관계",
  "Step": "한 단계",
  "stim": "스팀팩",
  "Stop running for each player": "플레이어별 실행 그만두기",
  "Stored in frames at Normal speed: 15 per game second.": "보통 속도 기준 프레임으로 저장됩니다 (게임 1초에 15).",
  "Stored in frames at Normal speed: 15 per game second. Verified: a Barracks trained a marine in a second (probe 8).": "보통 속도 기준 프레임으로 저장됩니다 (게임 1초에 15). 확인됨: 배럭이 마린을 1초 만에 생산했습니다 (probe 8).",
  "Stored in halves: a Zergling is 1.": "절반 단위로 저장됩니다. 저글링이 1입니다.",
  "string {n}": "문자열 {n}",
  "Subtract": "빼기",
  "Subtract a counter from another": "카운터를 다른 카운터에서 빼기",
  "Subtract {from} from {to}": "{to}에서 {from} 빼기",
  "supply": "보급",
  "Supply cap of a player": "플레이어의 보급 한도",
  "Supply provided by a unit type": "유닛 종류가 주는 보급",
  "Supply provided to a player": "플레이어가 받는 보급",
  "Supply used by a player": "플레이어가 쓰는 보급",
  "Supply used by a unit type": "유닛 종류가 쓰는 보급",
  "Switch": "스위치",
  "Switches set": "켜진 스위치",
  "Synced input (keys, clicks, mouse) through MSQC": "MSQC를 통한 동기화 입력 (키, 클릭, 마우스)",
  "Synced input needs {player} for itself, and the slot is set to {type}. Make it inactive in Scenario ▸ Players, or free another slot and remove the input rows to let Magenta pick again.": "동기화 입력은 {player}을(를) 전용으로 써야 하는데 이 슬롯이 {type}(으)로 설정되어 있습니다. 시나리오 ▸ 플레이어에서 비활성으로 바꾸거나, 다른 슬롯을 비우고 입력 행을 지워 Magenta가 다시 고르게 하세요.",
  "Synced input needs {player} for itself, and units on the map belong to it.": "동기화 입력은 {player}을(를) 전용으로 써야 하는데 맵에 그 플레이어의 유닛이 있습니다.",
  "Synced input owns {player}; this trigger runs for it too.": "{player}은(는) 동기화 입력 전용인데 이 트리거가 그 플레이어로도 실행됩니다.",
  "Synced input uses the {unit} type for its own command units, and the map has some placed. Remove them, or pick another unit type in the map's settings.": "동기화 입력은 {unit} 종류를 자체 명령 유닛으로 쓰는데 맵에 이 유닛이 배치되어 있습니다. 배치된 유닛을 지우거나 맵 설정에서 다른 유닛 종류를 고르세요.",
  "Synced input's own location slot ({n}) is no longer empty: a location was made there. Free it, or remove the input rows and add them again to pick another.": "동기화 입력 전용 로케이션 슬롯({n})이 더 이상 비어 있지 않습니다. 그 자리에 로케이션이 생겼습니다. 비우거나, 입력 행을 지우고 다시 추가해 다른 슬롯을 고르게 하세요.",
  "take": "감소",
  "take the speed upgrade": "속도 업그레이드 빼기",
  "Take the {units} {by} {measure}: {action}, center {location} on it, value into {counter}": "{units} 중 {measure|이} {by} 유닛: {action}, {location|을} 그 유닛 중심에, 값은 {counter}에",
  "Take the {units} {by} {point}: {action}, center {location} on it, value into {counter}": "{units} 중 {point}에 {by} 유닛: {action}, {location|을} 그 유닛 중심에, 값은 {counter}에",
  "Take the {units} {by}: {action}, center {location} on it, value into {counter}": "{units} 중 {by} 유닛: {action}, {location|을} 그 유닛 중심에, 값은 {counter}에",
  "Target acquisition range of a unit type": "유닛 종류의 대상 탐색 범위",
  "targeting something": "대상 지정 중",
  "teal": "청록",
  "Technologies": "기술",
  "Technology": "기술",
  "Technology researched by a player": "플레이어가 연구한 기술",
  "technology {n}": "기술 {n}",
  "Terran": "테란",
  "Text": "텍스트",
  "That is not trigger text": "트리거 텍스트가 아닙니다",
  "The air weapon of {unit} is {value}": "{unit}의 공중 무기: {value}",
  "The armor of {unit} is {cmp} {value}": "{unit}의 방어력이 {value} {cmp}",
  "The background music {file} is not in the map archive.": "배경 음악 {file}이(가) 맵 아카이브에 없습니다.",
  "The browser did not allow reading the clipboard": "브라우저가 클립보드 읽기를 허용하지 않았습니다",
  "The build failed: {why}. The map is unchanged.": "빌드에 실패했습니다: {why}. 맵은 바뀌지 않았습니다.",
  "The build time of {unit} is {cmp} {value}": "{unit}의 생산 시간이 {value} {cmp}",
  "The camera finds its location by name, and location {n} has none of its own.": "카메라는 로케이션을 이름으로 찾는데 로케이션 {n}에는 이름이 없습니다.",
  "The camera follows a location by its name, so only named locations are offered. It follows while a switch named cammove is set, so a trigger can turn it on and off; the switch and a helper location named cammoveLoc are made in this map at build time. A looped sound needs its length; a plain WAV's is read from the file.": "카메라는 로케이션을 이름으로 찾으므로 이름 있는 로케이션만 고를 수 있습니다. cammove라는 스위치가 켜져 있는 동안 따라가므로 트리거로 켜고 끌 수 있습니다. 이 스위치와 cammoveLoc이라는 보조 로케이션은 빌드할 때 이 맵에 만들어집니다. 반복 재생할 사운드는 길이가 필요하며, 일반 WAV는 파일에서 길이를 읽습니다.",
  "The camera follows a location, for everyone": "모두의 카메라가 로케이션을 따라감",
  "The camera follows location {n}, which the map no longer has.": "카메라가 맵에서 없어진 로케이션 {n}을(를) 따라갑니다.",
  "The camera needs one free location slot for its helper location.": "카메라의 보조 로케이션에 쓸 빈 로케이션 슬롯이 하나 필요합니다.",
  "The camera needs one free switch to turn it on and off.": "카메라를 켜고 끌 빈 스위치가 하나 필요합니다.",
  "The chat command \"{message}\": {problem}": "채팅 명령 \"{message}\": {problem}",
  "The chat said a command": "채팅으로 명령 입력",
  "The chat said {message} {mode}": "채팅 입력: {message} {mode}",
  "The cloak of placed unit {index} is {value}": "배치된 유닛 {index}의 은폐: {value}",
  "The command before the number: -set matches -set 250, and the number lands in the counter named Chat number": "숫자 앞의 명령입니다. -set은 -set 250과 맞고, 숫자는 Chat number라는 카운터에 들어갑니다",
  "The cooldown of {weapon} is {cmp} {value}": "{weapon}의 재사용 대기시간이 {value} {cmp}",
  "The cooldowns are written each time the trigger fires; to keep a unit from firing, the trigger must fire every cycle (preserved, with triggers running every frame).": "재사용 대기시간은 트리거가 실행될 때마다 쓰입니다. 유닛이 계속 공격하지 못하게 하려면 트리거가 매 주기 실행되어야 합니다 (보존, 트리거 매 프레임 실행).",
  "The countdown timer": "카운트다운 타이머",
  "The damage bonus per upgrade of {weapon} is {cmp} {value}": "{weapon}의 업그레이드당 추가 공격력이 {value} {cmp}",
  "The damage factor of {weapon} is {cmp} {value}": "{weapon}의 공격 횟수가 {value} {cmp}",
  "The damage of {weapon} is {cmp} {value}": "{weapon}의 공격력이 {value} {cmp}",
  "The destination. The order goes to one unit at a time through the location named Magenta scratch, which is Magenta's to move.": "목적지입니다. 명령은 Magenta scratch라는 로케이션을 거쳐 한 유닛씩 내려지며, 이 로케이션은 Magenta가 옮깁니다.",
  "The energy cost of {tech} is {cmp} {value}": "{tech}의 에너지 비용이 {value} {cmp}",
  "The energy of placed unit {index} is {cmp} {value}": "배치된 유닛 {index}의 에너지가 {value} {cmp}",
  "The eudplib plugin is not running: it is the library that builds EUD maps. Install or turn it on under Plugins ▸ Manage Plugins…": "eudplib 플러그인이 실행되고 있지 않습니다. EUD 맵을 빌드하는 라이브러리입니다. 플러그인 ▸ 플러그인 관리…에서 설치하거나 켜세요.",
  "The eudplib plugin is not running; install or turn it on under Plugins ▸ Manage Plugins…": "eudplib 플러그인이 실행되고 있지 않습니다. 플러그인 ▸ 플러그인 관리…에서 설치하거나 켜세요.",
  "The field's value — or the distance, for the nearest — goes into this counter; 0 when nothing matched.": "그 항목의 값(가장 가까운 유닛이면 거리)이 이 카운터에 들어갑니다. 맞는 유닛이 없으면 0입니다.",
  "The first level's cost; each further level adds the upgrade's own factor to it.": "첫 단계의 비용입니다. 다음 단계마다 업그레이드 고유의 증가량이 더해집니다.",
  "The first level's time, stored in frames at Normal speed: 15 per game second. Each further level adds the upgrade's own factor.": "첫 단계의 시간으로, 보통 속도 기준 프레임으로 저장됩니다 (게임 1초에 15). 다음 단계마다 업그레이드 고유의 증가량이 더해집니다.",
  "The game clock is {cmp} {value}": "게임 시계가 {value} {cmp}",
  "The game has run {cmp} {value}": "게임 진행 프레임이 {value} {cmp}",
  "The game is over for every player.": "모든 플레이어의 게임이 끝났습니다.",
  "The game speed is {value}": "게임 속도: {value}",
  "The gas cost of {tech} is {cmp} {value}": "{tech}의 가스 비용이 {value} {cmp}",
  "The gas cost of {unit} is {cmp} {value}": "{unit}의 가스 비용이 {value} {cmp}",
  "The gas cost of {upgrade} is {cmp} {value}": "{upgrade}의 가스 비용이 {value} {cmp}",
  "The gas of {player} is {cmp} {value}": "{player}의 가스가 {value} {cmp}",
  "The ground weapon of {unit} is {value}": "{unit}의 지상 무기: {value}",
  "The hallucination flag of placed unit {index} is {value}": "배치된 유닛 {index}의 환영 플래그: {value}",
  "The hit points of placed unit {index} is {cmp} {value}": "배치된 유닛 {index}의 체력이 {value} {cmp}",
  "The left-hand number of the top bar. The game recounts it when a unit is made or dies. Each race has its own table; a player's is the one for the race they play. Verified as a read (probe 9).": "위쪽 막대의 왼쪽 숫자입니다. 유닛이 생기거나 죽을 때 게임이 다시 셉니다. 종족마다 표가 따로 있으며, 플레이어에게는 자기 종족의 표가 쓰입니다. 읽기로 확인됨 (probe 9).",
  "The level of {upgrade} for {player} is {cmp} {value}": "{player}의 {upgrade} 단계가 {value} {cmp}",
  "The map changed since its last build, {when}{file}: that output is stale.": "마지막 빌드({when}{file}) 이후 맵이 바뀌었습니다. 그 결과물은 오래된 것입니다.",
  "The max hit points of {unit} is {cmp} {value}": "{unit}의 최대 체력이 {value} {cmp}",
  "The max shields of {unit} is {cmp} {value}": "{unit}의 최대 보호막이 {value} {cmp}",
  "The maximum level of {upgrade} is {cmp} {value}": "{upgrade}의 최대 단계가 {value} {cmp}",
  "The mineral cost of {tech} is {cmp} {value}": "{tech}의 미네랄 비용이 {value} {cmp}",
  "The mineral cost of {unit} is {cmp} {value}": "{unit}의 미네랄 비용이 {value} {cmp}",
  "The mineral cost of {upgrade} is {cmp} {value}": "{upgrade}의 미네랄 비용이 {value} {cmp}",
  "The minerals of {player} is {cmp} {value}": "{player}의 미네랄이 {value} {cmp}",
  "The minimum range of {weapon} is {cmp} {value}": "{weapon}의 최소 사거리가 {value} {cmp}",
  "The mouse's X on screen is {cmp} {value}": "화면 위 마우스 X가 {value} {cmp}",
  "The mouse's Y on screen is {cmp} {value}": "화면 위 마우스 Y가 {value} {cmp}",
  "The name comes from one of the map's strings, shown wherever the unit's name appears; the one type only. Remastered only.": "이름은 맵의 문자열 가운데 하나에서 가져오며, 유닛 이름이 나오는 곳마다 보입니다. 이 종류에만 적용됩니다. Remastered 전용.",
  "The next scenario is set to \"{name}\".": "다음 시나리오가 \"{name}\"(으)로 설정됩니다.",
  "The order row's scratch location ({n}) is gone; pick the order again to make one.": "명령 행의 작업용 로케이션({n})이 없어졌습니다. 명령을 다시 골라 새로 만드세요.",
  "The order row's target location ({n}) is gone.": "명령 행의 목표 로케이션({n})이 없어졌습니다.",
  "The owner of placed unit {index} is {value}": "배치된 유닛 {index}의 소유자: {value}",
  "The pick row centres location {n} on the unit, and the map no longer has it.": "고르기 행은 로케이션 {n}을(를) 유닛 중심에 두는데, 맵에 그 로케이션이 없습니다.",
  "The pick row measures from location {n}, which the map no longer has.": "고르기 행이 맵에서 없어진 로케이션 {n}에서부터 거리를 잽니다.",
  "The player at this computer is {value}": "이 컴퓨터의 플레이어: {value}",
  "The race of {player} is {value}": "{player}의 종족: {value}",
  "The race the player picked, once the game has started. Verified: read at the start of probe 9.": "게임이 시작된 뒤 플레이어가 고른 종족. 확인됨: probe 9 시작 때 읽음.",
  "The range of {weapon} is {cmp} {value}": "{weapon}의 사거리가 {value} {cmp}",
  "The research time of {tech} is {cmp} {value}": "{tech}의 연구 시간이 {value} {cmp}",
  "The research time of {upgrade} is {cmp} {value}": "{upgrade}의 연구 시간이 {value} {cmp}",
  "The right-hand number of the top bar, before the cap. The game recounts it when a depot, overlord or pylon is made or lost, so set it every frame to hold a value. Each race has its own table; a player's is the one for the race they play.": "위쪽 막대의 오른쪽 숫자로, 한도를 적용하기 전 값입니다. 서플라이 디포, 오버로드, 파일런이 생기거나 없어질 때 게임이 다시 세므로, 값을 유지하려면 매 프레임 설정하세요. 종족마다 표가 따로 있으며, 플레이어에게는 자기 종족의 표가 쓰입니다.",
  "The row centres location {n} on the unit, and the map no longer has it.": "이 행은 로케이션 {n}을(를) 유닛 중심에 두는데, 맵에 그 로케이션이 없습니다.",
  "The same number Set Resources changes, without the resource counter's sound.": "Set Resources가 바꾸는 것과 같은 값이지만, 자원 카운터 소리가 나지 않습니다.",
  "The screen's left edge on the map is {cmp} {value}": "맵 위 화면의 왼쪽 끝이 {value} {cmp}",
  "The screen's top edge on the map is {cmp} {value}": "맵 위 화면의 위쪽 끝이 {value} {cmp}",
  "The seconds the in-game clock shows. The earlier entry at 0x58D6F4 (the countdown timer) never fired; this one is the next dword. Verified: a line at 15 s (probe 8).": "게임 안 시계가 보여 주는 초입니다. 예전 항목 0x58D6F4(카운트다운 타이머)는 실행되지 않았고, 이것은 그다음 dword입니다. 확인됨: 15초에 한 줄 (probe 8).",
  "The shields of placed unit {index} is {cmp} {value}": "배치된 유닛 {index}의 보호막이 {value} {cmp}",
  "The sight range of {unit} is {cmp} {value}": "{unit}의 시야가 {value} {cmp}",
  "The size of {unit} is {value}": "{unit}의 크기: {value}",
  "The slot of {player} is {value}": "{player}의 슬롯: {value}",
  "The sound of {what} is not in the map.": "{what}의 사운드가 맵에 없습니다.",
  "The stance of {player} toward {other} is {value}": "{other}에 대한 {player}의 관계: {value}",
  "The supply provided by {unit} is {cmp} {value}": "{unit}이(가) 주는 보급이 {value} {cmp}",
  "The supply used by {unit} is {cmp} {value}": "{unit}이(가) 쓰는 보급이 {value} {cmp}",
  "The target acquisition range of {unit} is {cmp} {value}": "{unit}의 대상 탐색 범위가 {value} {cmp}",
  "The trigger timer is {cmp} {value}": "트리거 타이머가 {value} {cmp}",
  "The trigger's name, kept as its Comment action so every editor shows it": "트리거 이름입니다. 어느 편집기에서나 보이도록 Comment 액션으로 저장됩니다",
  "The trigger's name, shown by every trigger editor": "트리거 이름. 모든 트리거 편집기에 보입니다",
  "The triggers changed since this run started. Reset to run the list as it is now.": "이 실행을 시작한 뒤 트리거가 바뀌었습니다. 초기화하면 지금의 목록으로 실행합니다.",
  "The weakest, strongest, nearest or a random unit of a kind": "어떤 종류에서 가장 약한, 가장 강한, 가장 가까운, 또는 무작위 유닛",
  "The X of placed unit {index} is {cmp} {value}": "배치된 유닛 {index}의 X가 {value} {cmp}",
  "The Y of placed unit {index} is {cmp} {value}": "배치된 유닛 {index}의 Y가 {value} {cmp}",
  "The {key} key is {value}": "{key} 키: {value}",
  "The {race} supply cap of {player} is {cmp} {value}": "{player}의 {race} 보급 한도가 {value} {cmp}",
  "The {race} supply provided to {player} is {cmp} {value}": "{player}의 {race} 보급 제공량이 {value} {cmp}",
  "The {race} supply used by {player} is {cmp} {value}": "{player}의 {race} 보급 사용량이 {value} {cmp}",
  "Then: {actions}.": "그러면: {actions}.",
  "This death counter is used by another plugin's generated triggers.": "이 데스 카운터는 다른 플러그인이 만든 트리거가 쓰고 있습니다.",
  "This map has no triggers yet. Add one with New.": "이 맵에는 아직 트리거가 없습니다. 새로 만들기로 추가하세요.",
  "This map has not been built yet.": "이 맵은 아직 빌드하지 않았습니다.",
  "This map's Magenta data could not be read ({detail}). Its folders, counter names and build rows are hidden, and the triggers cannot be changed here until the data is dropped.": "이 맵의 Magenta 데이터를 읽을 수 없습니다({detail}). 폴더, 카운터 이름, 빌드 행이 숨겨지며, 데이터를 버리기 전까지는 여기서 트리거를 바꿀 수 없습니다.",
  "This map's Magenta data was written by a newer Magenta (version {v}). Its folders, counter names and build rows are hidden, and the triggers cannot be changed here until Magenta is updated or the data is dropped.": "이 맵의 Magenta 데이터는 더 새로운 Magenta(버전 {v})가 썼습니다. 폴더, 카운터 이름, 빌드 행이 숨겨지며, Magenta를 업데이트하거나 데이터를 버리기 전까지는 여기서 트리거를 바꿀 수 없습니다.",
  "This trigger creates a {unit}, the type synced input keeps for itself.": "이 트리거는 동기화 입력 전용 종류인 {unit}을(를) 만듭니다.",
  "This trigger has no actions.": "이 트리거에는 액션이 없습니다.",
  "tick to pretend it holds": "체크하면 맞는 것으로 칩니다",
  "tiles": "타일",
  "times": "×",
  "to": "설정:",
  "To": "도착",
  "To: the top-left corner lands on x, y. By: the whole location shifts by x, y from where it is (negative goes left or up).": "좌표로: 왼쪽 위 모서리가 x, y에 옵니다. 만큼: 로케이션 전체가 지금 자리에서 x, y만큼 옮겨집니다 (음수는 왼쪽이나 위쪽).",
  "toggle": "전환",
  "Toggle action": "액션 켜기/끄기",
  "Toggle condition": "조건 켜기/끄기",
  "Toggle trigger": "트리거 켜기/끄기",
  "Total": "합계",
  "Toward": "상대",
  "Transmission from {Unit} at {Location}: {Text}, {WAV} for {WAV duration} ms, shown {Modifier} {Duration} ms ({Display})": "{Location}의 {Unit}에게서 통신: {Text}, {WAV} {WAV duration}ms, 표시 시간 {Modifier} {Duration}ms ({Display})",
  "Transmission {Text} from {Slot}, {WAV}, shown {Modifier} {Amount} for {Duration} ms": "{Slot}에서 통신 {Text}, {WAV}, 표시 시간 {Modifier} {Amount}, {Duration}ms",
  "Trigger timer": "트리거 타이머",
  "trigger {n}": "트리거 {n}",
  "Trigger {n}": "트리거 {n}",
  "Triggers Magenta generates for this one": "Magenta가 이 트리거를 위해 만드는 트리거",
  "Triggers run every frame": "트리거가 매 프레임 실행됩니다",
  "Triggers run every frame (turbo)": "트리거가 매 프레임 실행됨 (터보)",
  "Triggers run every two seconds": "트리거가 2초마다 실행됨",
  "Triggers run {clock}": "트리거가 {clock} 실행됩니다",
  "Turn on Run triggers every frame in the ⋯ menu for this one.": "이 레시피는 ⋯ 메뉴에서 트리거 매 프레임 실행을 켜야 합니다.",
  "Two chat commands say \"{message}\"; the second never fires on its own.": "\"{message}\" 채팅 명령이 두 개입니다. 두 번째는 따로 실행되지 않습니다.",
  "Two records: the palette entry the player's units are drawn in, and the one the minimap uses. Takes effect at once, for every unit of the player.": "레코드 2개: 플레이어 유닛을 그리는 팔레트 항목과 미니맵에 쓰는 항목. 플레이어의 모든 유닛에 바로 적용됩니다.",
  "Type of a placed unit": "배치된 유닛의 종류",
  "Type the message players will send.": "플레이어가 보낼 메시지를 입력하세요.",
  "un-hallucinate": "환영 해제",
  "unable to burrow": "버로우 불가",
  "unable to cloak": "은폐 불가",
  "unavailable": "사용 불가",
  "under attack": "공격받는 중",
  "Undo {what}": "실행 취소: {what}",
  "Unit": "유닛",
  "Unit at": "유닛 위치",
  "Unit name…": "유닛 이름…",
  "unit type id": "유닛 종류 번호",
  "Units": "유닛",
  "Units and buildings": "유닛과 건물",
  "Units made after this draw as the other type; the ones already on the map keep their look. Stats, size and weapons stay the type's own.": "이후에 만든 유닛은 다른 종류의 모습으로 그려지고, 이미 맵에 있는 유닛은 모습을 유지합니다. 능력치, 크기, 무기는 원래 종류 그대로입니다.",
  "Unmute unit speech": "유닛 음성 켜기",
  "Unname counter": "카운터 이름 없애기",
  "Unpause the countdown timer": "카운트다운 타이머 재개",
  "Unpause the game": "게임 재개",
  "Untitled trigger — type a name": "이름 없는 트리거 — 이름을 입력하세요",
  "up": "떼어짐",
  "up by": "추가:",
  "Up to 500 cycles: until someone wins or loses, or nothing has happened for 50 cycles": "최대 500주기. 누군가 이기거나 지거나, 50주기 동안 아무 일도 없을 때까지",
  "Up to 78 bytes, which is what the game lets a player type.": "게임에서 플레이어가 입력할 수 있는 길이인 78바이트까지입니다.",
  "Upgrade": "업그레이드",
  "Upgrade level of a player": "플레이어의 업그레이드 단계",
  "upgrade {n}": "업그레이드 {n}",
  "Upgrades": "업그레이드",
  "used by": "쓰는 트리거:",
  "user selectable": "사용자 선택",
  "Verified (probe 8). A value past the unit's maximum shows for a frame and is clamped back by the game, so 250 on a Ghost reads 200/200.": "확인됨 (probe 8). 유닛 최대치를 넘는 값은 한 프레임 보였다가 게임이 되돌리므로, 고스트에 250을 쓰면 200/200으로 읽힙니다.",
  "Verified (probe 9).": "확인됨 (probe 9).",
  "Verified as a write (probe 9): the unit is labelled a hallucination and takes hallucination damage, but the tint and the timed death come from a real cast, not this bit.": "쓰기로 확인됨 (probe 9): 유닛이 환영으로 표시되고 환영 피해를 받지만, 색조와 시간이 지나 죽는 것은 이 비트가 아니라 실제 마법에서 옵니다.",
  "Verified in Remastered 2026-09-12. Slots: the first placed unit is slot 0 and later ones count down from 1699 (verified in Remastered 2026-09-12); the chip picks a unit on the map and works the slot out. Start locations take no slot; nor does a unit of a human player who is not in the game (it is removed at load), so slots after one shift by one when that player is missing.": "2026-09-12 Remastered에서 확인됨. 슬롯: 처음 배치된 유닛이 슬롯 0이고 그 뒤로는 1699부터 거꾸로 셉니다 (2026-09-12 Remastered에서 확인). 칩에서 맵의 유닛을 고르면 슬롯을 계산해 줍니다. 시작 위치는 슬롯을 차지하지 않고, 게임에 없는 사람 플레이어의 유닛도 불러올 때 지워지므로 차지하지 않습니다. 그래서 그 플레이어가 없으면 뒤의 슬롯이 하나씩 밀립니다.",
  "Verified: +500 gas (probe 8).": "확인됨: 가스 +500 (probe 8).",
  "Verified: a depot made after the write provided 30 (probe 9).": "확인됨: 쓰기 뒤에 만든 서플라이 디포가 보급 30을 주었습니다 (probe 9).",
  "Verified: a marine made after the write had 100 HP (probe 8).": "확인됨: 쓰기 뒤에 만든 마린의 체력이 100이었습니다 (probe 8).",
  "Verified: a placed Zealot set to 0 shields (probe 8).": "확인됨: 배치된 질럿의 보호막을 0으로 설정 (probe 8).",
  "Verified: Infantry Weapons set to 3 showed on the marines (probe 8).": "확인됨: 보병 공격력을 3으로 설정한 것이 마린에게 보였습니다 (probe 8).",
  "Verified: Lockdown and Personnel Cloaking researched at the start of probe 8, and the ghost could cast.": "확인됨: probe 8 시작 때 락다운과 개인 은폐가 연구되었고, 고스트가 쓸 수 있었습니다.",
  "Verified: marines given the Arclite Shock Cannon fired it (probe 9). Units already on the map switch too.": "확인됨: 아크라이트 충격포를 받은 마린이 그것을 쐈습니다 (probe 9). 이미 맵에 있는 유닛도 바뀝니다.",
  "Verified: marines with no air weapon ignored an overlord (probe 9).": "확인됨: 공중 무기가 없는 마린이 오버로드를 무시했습니다 (probe 9).",
  "Verified: read while a ghost was cloaked (probe 9).": "확인됨: 고스트가 은폐한 동안 읽음 (probe 9).",
  "Vision of {player} for {other} is {value}": "{other}에게 {player}의 시야 공유: {value}",
  "Wait {Milliseconds} ms": "{Milliseconds}ms 대기",
  "waiting inside its actions": "액션 안에서 기다리는 중",
  "waiting until {s} s": "{s}초까지 대기",
  "waits {s} s": "{s}초 대기",
  "walk through anything": "무엇이든 통과",
  "WAV": "WAV",
  "WAV duration": "WAV 길이",
  "Weapon": "무기",
  "weapon cooldown": "무기 재사용 대기시간",
  "weapon {n}": "무기 {n}",
  "Weapons": "무기",
  "What a cast of the spell takes. Verified: lockdown at 10 energy (probe 8).": "마법을 한 번 쓸 때 드는 에너지입니다. 확인됨: 에너지 10으로 락다운 (probe 8).",
  "What a player types in chat; ^…$ writes a pattern, as in ^-give .*$": "플레이어가 채팅에 입력하는 말입니다. ^…$는 ^-give .*$처럼 패턴을 씁니다",
  "What concussive and explosive damage scale by: small takes full concussive damage and half explosive, large the other way round. Verified: a vulture took 5 off a large marine (probe 9).": "진동형과 폭발형 공격력이 얼마나 들어갈지 정합니다. 소형은 진동형을 모두, 폭발형을 절반 받고, 대형은 그 반대입니다. 확인됨: 벌처가 대형 마린에게 5를 입혔습니다 (probe 9).",
  "What the provided supply is capped at, 200 in a normal game. Each race has its own table; a player's is the one for the race they play.": "받는 보급의 한도로, 일반 게임에서는 200입니다. 종족마다 표가 따로 있으며, 플레이어에게는 자기 종족의 표가 쓰입니다.",
  "What the slot holds once the game has started: a human, a computer, or nothing. Verified: read at the start of probe 9.": "게임이 시작된 뒤 슬롯에 있는 것: 사람, 컴퓨터, 또는 없음. 확인됨: probe 9 시작 때 읽음.",
  "When a unit comes to {location}": "{location}에 유닛이 오면",
  "When the player's unit dies, wait five seconds and create it again at the location. Change the unit and the location.": "플레이어의 유닛이 죽으면 5초 기다린 뒤 로케이션에 다시 만듭니다. 유닛과 로케이션을 바꾸세요.",
  "When this {unit} dies": "이 {unit}이(가) 죽으면",
  "When this {unit} is at {location}": "이 {unit}이(가) {location}에 있으면",
  "Where the map stands against its last build; click for Build EUD map…": "마지막 빌드와 비교한 맵의 상태입니다. 클릭하면 EUD 맵 빌드…",
  "Whether a player has left": "플레이어가 나갔는지",
  "white": "하양",
  "Whoever brings a unit to {location} gets the {unit}": "{location}에 유닛을 가져온 플레이어가 {unit}을(를) 받음",
  "Width × height in map pixels, 32 per tile; 0 keeps the location's own size": "맵 픽셀 단위의 너비 × 높이 (타일당 32). 0이면 로케이션 크기를 그대로 둡니다",
  "Win by holding a location": "로케이션을 지켜서 승리",
  "wins": "승리",
  "With a number, the message is a prefix and the number typed after it goes into the counter named Chat number.": "숫자를 받으면 메시지는 앞부분이 되고, 그 뒤에 입력한 숫자가 Chat number라는 카운터에 들어갑니다.",
  "with the greatest": "가장 높은",
  "with the least": "가장 낮은",
  "With triggers running every frame, a Wait blocks the owner's other triggers for its whole length.": "트리거가 매 프레임 실행되면 Wait은 그 시간 내내 소유자의 다른 트리거를 막습니다.",
  "with {group} standing for the player": "{group}이(가) 그 플레이어를 뜻함",
  "won": "승리",
  "write only": "쓰기 전용",
  "Writes memory at 0x{hex}, which the catalogue does not know.": "카탈로그에 없는 메모리 0x{hex}에 씁니다.",
  "Writing it did nothing in Remastered (probe 5, 2026-09-14), so it is a read only: what the speed setting is.": "Remastered에서는 써도 아무 일이 없었으므로 (probe 5, 2026-09-14) 읽기 전용입니다: 속도 설정이 무엇인지.",
  "x": "x",
  "X position of a placed unit": "배치된 유닛의 X 위치",
  "y": "y",
  "Y position of a placed unit": "배치된 유닛의 Y 위치",
  "yellow": "노랑",
  "Zerg": "저그",
  "{action} to {value}": "{action}: {value}",
  "{action} {location}": "{action} {location}",
  "{action} {n} {field}": "{field} {n} {action}",
  "{action} {player}": "{action} {player}",
  "{action}: {effect} for {seconds} s": "{action}: {effect} {seconds}초",
  "{action}: {location}": "{action}: {location}",
  "{a} is {relation} {b}": "{a|이} {b} {relation}",
  "{Counter name} for a counter's value, {Player 1} for a name, {Player 1's colour} to switch colour; the buttons insert the game's own codes": "{Counter name}은(는) 카운터 값, {Player 1}은(는) 플레이어 이름, {Player 1's colour}은(는) 색 바꾸기입니다. 버튼은 게임의 코드를 넣습니다",
  "{counter} is {cmp} {amount}": "{counter|이} {amount} {cmp}",
  "{count} {unit} for {player} at {location}": "{location}에 {player}의 {unit} {count}",
  "{list} and {last}": "{list}, {last}",
  "{n, plural, one {# build row} other {# build rows}} (text, maths, unit passes, checks)": "{n, plural, other {빌드 행 #개}} (텍스트, 계산, 유닛 순회, 검사)",
  "{n, plural, one {# chat command} other {# chat commands}}": "{n, plural, other {채팅 명령 #개}}",
  "{n, plural, one {# row is} other {# rows are}} shared with the original: editing it in one changes the other.": "{n, plural, other {행 #개를}} 원본과 함께 씁니다. 한쪽에서 편집하면 다른 쪽도 바뀝니다.",
  "{n, plural, one {0x{hex}, # byte} other {0x{hex}, # bytes}}": "{n, plural, other {0x{hex}, #바이트}}",
  "{n, plural, one {Fix the problem above first.} other {Fix the # problems above first.}}": "{n, plural, other {위의 문제 #개를 먼저 고치세요.}}",
  "{n, plural, one {It fires when {when}.} =2 {It fires when {when} both hold.} other {It fires when {when} all hold.}}": "{n, plural, =1 {다음 조건일 때 실행됩니다: {when}.} =2 {다음 두 조건이 모두 맞을 때 실행됩니다: {when}.} other {다음 조건이 모두 맞을 때 실행됩니다: {when}.}}",
  "{n, plural, one {Its Waits hold the owner's other triggers for # second in all, every time it fires.} other {Its Waits hold the owner's other triggers for # seconds in all, every time it fires.}}": "{n, plural, other {실행될 때마다 Wait이 소유자의 다른 트리거를 모두 합해 #초 동안 멈춥니다.}}",
  "{n, plural, one {Its Waits hold the owner's other triggers for # second in all.} other {Its Waits hold the owner's other triggers for # seconds in all.}}": "{n, plural, other {Wait이 소유자의 다른 트리거를 모두 합해 #초 동안 멈춥니다.}}",
  "{n, plural, one {One disabled condition is ignored.} other {# disabled conditions are ignored.}}": "{n, plural, other {비활성화된 조건 #개는 무시됩니다.}}",
  "{n, plural, one {The eight location slots the players' mice use ({from}–{to}) must stay empty; slot {taken} is in use.} other {The eight location slots the players' mice use ({from}–{to}) must stay empty; slots {taken} are in use.}}": "{n, plural, other {플레이어 마우스용 로케이션 슬롯 8개({from}–{to})는 비어 있어야 하는데 슬롯 {taken}을(를) 쓰고 있습니다.}}",
  "{name} — {where}, Remastered: {access}.": "{name} — {where}, Remastered: {access}.",
  "{n} groups": "그룹 {n}개",
  "{n} records from 0x{hex}": "0x{hex}부터 레코드 {n}개",
  "{n} units": "유닛 {n}기",
  "{n}-bit": "{n}비트",
  "{owner} brings at least 1 {unit} to {location}": "{owner}이(가) {location}에 {unit}을(를) 1기 이상 가져옴",
  "{owner}'s deaths of {unit} reach 1 (any {unit} of theirs, not only this one)": "{owner}의 {unit} 데스가 1이 되면 (이 유닛만이 아니라 그 플레이어의 {unit} 모두)",
  "{players} each run this trigger on their own.": "{players}이(가) 각자 이 트리거를 실행합니다.",
  "{Player} accumulates {Comparison} {Amount} {Resource}": "{Player}의 {Resource} 누적량이 {Amount} {Comparison}",
  "{Player} brings {Comparison} {Amount} {Unit} to {Location}": "{Player|이} {Location}에 {Unit|을} {Amount}기 {Comparison} 가져옴",
  "{player} clicked the {button} button": "{player|이} 마우스 {button} 버튼을 클릭함",
  "{Player} commands {Comparison} {Amount} {Unit}": "{Player|이} {Unit|을} {Amount}기 {Comparison} 보유",
  "{Player} has killed {Comparison} {Amount} {Unit}": "{Player|이} {Unit|을} {Amount}기 {Comparison} 처치",
  "{Player} has suffered {Comparison} {Amount} deaths of {Unit}": "{Player}의 {Unit} 데스가 {Amount} {Comparison}",
  "{Player} has {Comparison} {Amount} opponents remaining": "{Player}의 남은 상대가 {Amount}명 {Comparison}",
  "{player} pressed {key}": "{player|이} {key} 키를 누름",
  "{player} runs this trigger.": "{player}이(가) 이 트리거를 실행합니다.",
  "{player} {value}": "{player}: {value}",
  "{player}'s mouse": "{player}의 마우스",
  "{player}'s mouse is over {location}": "{player}의 마우스가 {location} 위에 있음",
  "{Player}'s {Score} score is {Comparison} {Amount}": "{Player}의 {Score} 점수가 {Amount} {Comparison}",
  "{player}'s {unit} deaths": "{player}의 {unit} 데스",
  "{point} within {radius}": "{point}에서 {radius} 이내",
  "{State} computer players on the leader board": "리더보드의 컴퓨터 플레이어: {State}",
  "{State} invincibility for {Unit} owned by {Player} at {Location}": "{Location}에 있는 {Player}의 {Unit} 무적: {State}",
  "{State} the doodad state of {Unit} owned by {Player} at {Location}": "{Location}에 있는 {Player}의 {Unit} 장식물 상태: {State}",
  "{Switch} is {State}": "{Switch}: {State}",
  "{Switch}: {Action}": "{Switch}: {Action}",
  "{s} s": "{s}초",
  "{s} s (paused)": "{s}초 (일시 정지)",
  "{tech} for {player} is {value}": "{player}의 {tech}: {value}",
  "{unit} (slot {n})": "{unit} (슬롯 {n})",
  "{unit} is {value}": "{unit}: {value}",
  "{unit} owned by {owner} at {location}": "{location}에 있는 {owner}의 {unit}",
  "{what} has no text.": "{what}에 텍스트가 없습니다.",
  "{what} is each computer's own, and this trigger changes the game for everyone: the players can go out of sync. For a key or a click, use a synced press (search \"key press\"); a read like this fits only what one screen shows.": "{what}은(는) 컴퓨터마다 따로 가지는 값인데, 이 트리거는 모두의 게임을 바꿉니다. 플레이어들의 동기화가 어긋날 수 있습니다. 키나 클릭에는 동기화된 입력을 쓰세요(\"key press\" 검색). 이런 읽기는 한 화면에만 보이는 것에만 맞습니다.",
  "{what} names location {n}, which the map no longer has.": "{what}이(가) 맵에서 없어진 로케이션 {n}을(를) 가리킵니다.",
  "{what} names no location.": "{what}에 로케이션이 지정되지 않았습니다.",
  "{what} names string {n}, which the map does not have.": "{what}이(가) 맵에 없는 문자열 {n}을(를) 가리킵니다.",
  "{what}: generated from the trigger it belongs to. Edit that trigger in Magenta; the run is rebuilt with it.": "{what}: 이 트리거가 속한 트리거에서 만들어졌습니다. 그 트리거를 Magenta에서 편집하면 함께 다시 만들어집니다.",
};
