/**
 * The right pane: the open trigger — its title (the Comment action), its owners, its
 * conditions and actions as rows with an add row under each, and the problems the
 * checks found. A trigger inside another plugin's claimed run shows that plugin's
 * sentence and its Open button instead.
 */
import type { PluginApi, ActionRecord, ConditionRecord, TriggerRecord } from "@scm-js/plugin-api";
import { ActionType, ConditionType, Comparison, SetModifier, MAX_ACTIONS, MAX_CONDITIONS, PLAYER_GROUP_COUNT } from "../../vendor/triggers";
import { enumerated } from "../catalogue";
import { check, type Problem } from "../model/checks";
import { actionSpans, lowerActions, lowerCondition } from "../model/eud";
import { commentIndex, liveActions, liveConditions, owners, setActionDisabled, setConditionDisabled, setOwners } from "../model/records";
import { cellKey, playerSlots } from "../model/counters";
import type { Host } from "./host";
import { addRow, type Pick, type Picked } from "./palette";
import { fillAction, fillCondition, fillEud, type Entity } from "../model/parse";
import { pickChoice } from "./chips";
import { renderGroupRow, renderRow, type RowContext } from "./rows";
import { compareOf, counterExpansionOf, newCompare, newCounterStep, renderCompare, renderCounterExpansion } from "./expansionRows";
import { flagAction } from "../model/expansions";
import { conditionRowOf, hookOf, newChat, newHook, newInput, newScan, renderConditionRow, renderHook } from "./buildRows";
import { sharedElsewhere } from "../model/ownership";
import type { Store } from "./store";
import { explain, type Ref } from "../model/explain";
import { cellOf } from "../model/counters";
import { cellLabel } from "./expansionRows";
import { actionWords, conditionWords, titleOf } from "./words";

export interface EditorDeps {
  api: PluginApi;
  host: Host;
  store: Store;
}

/** Fill `root` with the editor for the selected trigger. */
export function renderEditor(deps: EditorDeps, root: HTMLElement): void {
  const { api, host, store } = deps;
  const el = api.ui.el;
  const t = api.i18n.t;
  root.replaceChildren();
  const index = store.selected;
  if (index === null || !store.list[index]) {
    root.append(el("div", { className: "mg-empty" }, store.list.length ? t("Pick a trigger on the left, or add one.") : t("This map has no triggers yet. Add one with New.")));
    return;
  }
  const trigger = store.list[index];
  const claim = host.claims(store.list).find((c) => index >= c.start && index < c.start + c.count);
  if (claim && claim.pluginId !== api.plugin.id) {
    root.append(el("div", { className: "mg-locked" },
      el("div", {}, t("Generated by {what}: edit it there, not here.", { what: claim.label })),
      el("div", { className: "row" }, api.ui.widgets.button(t("Open {plugin}", { plugin: claim.badge }), { onClick: () => api.commands.run(`${claim.pluginId}.open`, { index }) })),
    ));
    return;
  }

  const namer = host.namer(store.sidecar);
  const extra = host.extra();
  const ctx: RowContext = { api, host, store, namer, extra, triggerIndex: index };
  const claimedCells = new Set<number>();
  for (const c of host.claims(store.list)) {
    if (c.pluginId === api.plugin.id) continue;
    for (let i = c.start; i < c.start + c.count; i++) {
      const tr = store.list[i];
      if (!tr) continue;
      const own = owners(tr);
      for (const cc of tr.conditions) if (cc.type === ConditionType.Deaths && cc.player < PLAYER_GROUP_COUNT && cc.unitId < 228) for (const p of playerSlots(cc.player, own)) claimedCells.add(cellKey(p, cc.unitId));
      for (const a of tr.actions) if (a.type === ActionType.SetDeaths && a.player < PLAYER_GROUP_COUNT && a.unitId < 228) for (const p of playerSlots(a.player, own)) claimedCells.add(cellKey(p, a.unitId));
    }
  }
  const perPlayer = store.sidecar.expansions.find((x): x is Extract<typeof x, { kind: "forEachPlayer" }> => x.kind === "forEachPlayer" && x.anchor.i === store.cleanIndex(index));
  const problems = check(trigger, {
    everyFrame: store.sidecar.settings.everyFrame, locationExists: (n) => host.locationExists(n), stringExists: (i) => host.stringExists(i), wavPresent: (i) => host.wavPresent(i), claimedCells, template: !!perPlayer,
    locationName: (n) => namer.location(n),
    deferredLocation: (a) => {
      const hook = hookOf(store, a);
      if (!hook) return null;
      if (hook.kind === "setloc") return hook.location;
      if (hook.kind === "pick") return hook.locate ?? (hook.do && "locate" in hook.do ? hook.do.locate : null);
      if (hook.kind === "foreach" && "locate" in hook.do) return hook.do.locate;
      return null;
    },
  });
  const general = problems.filter((p) => !p.at);
  const at = (kind: "condition" | "action", i: number): Problem[] => problems.filter((p) => p.at?.kind === kind && p.at.index === i);

  const replace = (label: string, next: TriggerRecord) => store.replace(index, next, label);

  /* ── Title ── */
  const ci = commentIndex(trigger);
  const titleText = ci >= 0 ? namer.string(trigger.actions[ci].text) ?? "" : "";
  const title = el("input", { className: "input", type: "text", placeholder: t("Untitled trigger — type a name"), value: titleText, title: t("The trigger's name, kept as its Comment action so every editor shows it") }) as HTMLInputElement;
  const commitTitle = () => {
    const text = title.value.trim();
    if (text === titleText || (!text && ci < 0)) return;
    store.commit(t("Rename trigger"), (intern) => store.list.map((tr, i) => {
      if (i !== index) return tr;
      const actions = [...tr.actions];
      if (ci < 0) actions.unshift({ ...api.triggers.newAction(ActionType.Comment), text: intern(text) });
      else if (text) actions[ci] = { ...actions[ci], text: intern(text) };
      else actions.splice(ci, 1);
      return { ...tr, actions };
    }));
  };
  title.addEventListener("change", commitTitle);
  title.addEventListener("keydown", (e) => { if (e.key === "Enter") { e.preventDefault(); title.blur(); } });
  root.append(el("div", { className: "mg-titlebar" }, title));

  /* ── Players ── */
  const own = owners(trigger);
  const playersRow = el("div", { className: "mg-players" }, el("span", { className: "hint" }, t("Runs for")));
  const groups = host.playerGroups();
  const players = host.players();
  for (const g of own) {
    const chip = el("button", { type: "button", className: "mg-chip", title: t("Click to remove") }, g < 12 && players[g]?.color ? el("span", { className: "mg-dot", style: `background:${players[g].color}` }) : null, groups.find((x) => x.value === g)?.label ?? String(g)) as HTMLButtonElement;
    chip.addEventListener("click", () => replace(t("Change owners"), setOwners(trigger, own.filter((x) => x !== g))));
    playersRow.append(chip);
  }
  const addOwner = el("button", { type: "button", className: "mg-chip", title: t("Add a player or group") }, "+") as HTMLButtonElement;
  addOwner.addEventListener("click", () => pickChoice(api, addOwner, groups.filter((g) => !own.includes(g.value)).map((g) => ({ value: g.value, label: g.label, color: g.value < 12 ? players[g.value]?.color ?? null : undefined })), (v) => replace(t("Change owners"), setOwners(trigger, [...own, v])), { width: 220 }));
  playersRow.append(addOwner);
  if (perPlayer) {
    playersRow.replaceChildren(el("span", { className: "hint" }, t("Runs once for each of")), ...perPlayer.players.map((p) => el("span", { className: "mg-chip" }, players[p]?.color ? el("span", { className: "mg-dot", style: `background:${players[p].color}` }) : null, groups.find((x) => x.value === p)?.label ?? String(p))), el("span", { className: "hint" }, t("with {group} standing for the player", { group: groups.find((x) => x.value === perPlayer.placeholder)?.label ?? "" })));
  }
  root.append(playersRow);
  for (const p of general) root.append(el("div", { className: `mg-problem ${p.level}`, style: "padding-left:6px" }, p.text));

  /* ── Conditions ── */
  const conditions = liveConditions(trigger);
  const condSection = el("div", { className: "mg-section" }, el("div", { className: "mg-section-head" }, t("Conditions"), el("span", { className: "grow" }), el("span", { className: "hint" }, `${conditions.length}/${MAX_CONDITIONS}`)));
  const writeConditions = (label: string, next: ConditionRecord[]) => replace(label, { ...trigger, conditions: next });
  const cmp = compareOf(store, index, trigger);
  conditions.forEach((c, i) => {
    const brow = conditionRowOf(store, c);
    if (brow) {
      const sentence = el("span", { className: "mg-sentence" });
      renderConditionRow(api, host, store, brow, sentence, (next) => writeConditions(t("Edit condition"), conditions.map((x, j) => (j === i ? next : x))));
      // A scan is this trigger's own unless another reads its cell; a chat command is shared by every trigger on its message.
      const ownRecord = brow.kind === "scan" && !sharedElsewhere(store.list, brow.record, index) ? brow.record.id : null;
      const remove = api.ui.widgets.button("✕", { ghost: true, title: t("Remove"), onClick: () => store.commit(t("Remove condition"), () => store.list.map((tr, j) => (j !== index ? tr : { ...tr, conditions: conditions.filter((_, k) => k !== i) })), ownRecord ? { sidecar: { builds: store.sidecar.builds.filter((b) => b.id !== ownRecord) } } : {}) });
      condSection.append(el("div", {}, el("div", { className: "mg-row", tabIndex: 0 }, sentence, el("span", { className: "mg-tools" }, remove))));
      return;
    }
    if (cmp && cmp.rows.includes(i)) {
      if (i !== cmp.rows[0]) return;
      const sentence = el("span", { className: "mg-sentence" });
      renderCompare(api, host, store, index, trigger, cmp, sentence);
      const remove = api.ui.widgets.button("✕", { ghost: true, title: t("Remove"), onClick: () => store.commit(t("Remove comparison"), () => store.list.map((tr, j) => (j !== index ? tr : { ...tr, conditions: conditions.filter((_, k) => !cmp.rows.includes(k)) })), { sidecar: { expansions: store.sidecar.expansions.filter((x) => x.id !== cmp.x.id) } }) });
      condSection.append(el("div", {}, el("div", { className: "mg-row", tabIndex: 0 }, sentence, el("span", { className: "mg-tools" }, remove))));
      return;
    }
    condSection.append(renderRow(ctx, "condition", i, c, at("condition", i), {
      onChange: (rec) => writeConditions(t("Edit condition"), conditions.map((x, j) => (j === i ? rec : x))),
      onChangeWithText: (text, apply) => store.commit(t("Edit condition"), (intern) => store.list.map((tr, j) => (j !== index ? tr : { ...tr, conditions: conditions.map((x, k) => (k === i ? apply(intern(text)) : x)) }))),
      onRemove: () => writeConditions(t("Remove condition"), conditions.filter((_, j) => j !== i)),
      onMove: (d) => { const to = i + d; if (to < 0 || to >= conditions.length) return; const next = [...conditions]; [next[i], next[to]] = [next[to], next[i]]; writeConditions(t("Move condition"), next); },
      onToggle: () => writeConditions(t("Toggle condition"), conditions.map((x, j) => (j === i ? setConditionDisabled(x, !(x.flags & 2)) : x))),
    }));
  });
  if (conditions.length < MAX_CONDITIONS) condSection.append(addRow(api, "condition", ({ pick, entities, query }: Picked) => {
    if (pick.kind === "build") {
      const insert = (label: string, condition: ConditionRecord, sidecar: Record<string, unknown>) => store.commit(label, () => store.list.map((tr, j) => (j !== index ? tr : { ...tr, conditions: [...conditions, condition] })), { sidecar });
      if (pick.what === "chat") {
        const withNumber = /\b(number|argument|amount|value)\b/i.test(query);
        const message = /^"?(.+?)"?$/.exec(query.replace(/^(the )?chat (said|command)\s*/i, "").replace(/\b(with|followed by) a (number|argument|amount|value)\b/i, "").trim())?.[1];
        const made = newChat(host, store, message && message !== query.trim() ? message : withNumber ? "-set" : undefined, withNumber ? "number" : null);
        if (!made) { api.ui.toast({ kind: "error", title: t("No free counter cell for the chat command") }); return; }
        insert(t("Add chat command"), made.condition, { builds: made.builds, chat: made.chat, ...(made.counters ? { counters: made.counters } : {}) });
      } else if (pick.what === "scan") {
        const made = newScan(host, store, query, entities.find((e) => e.kind === "unit")?.value ?? 0);
        if (!made) { api.ui.toast({ kind: "error", title: t("No free counter cell for the check") }); return; }
        insert(t("Add unit check"), made.condition, { builds: made.builds });
      } else if (pick.what === "key" || pick.what === "click" || pick.what === "mouseIn") {
        const key = entities.find((e) => e.kind === "key");
        const loc = entities.find((e) => e.kind === "location");
        const made = newInput(host, store, pick.what, { code: key?.value, button: /right/i.test(query) ? "R" : "L", location: loc?.value });
        if (!made) { api.ui.toast({ kind: "error", title: t("No room for synced input"), detail: t("It needs a free counter unit and, for the mouse, nine free location slots.") }); return; }
        insert(t("Add input"), made.condition, { msqc: made.msqc });
      }
      return;
    }
    if (pick.kind === "expansion") {
      if (cmp) { api.ui.toast({ kind: "info", title: t("One comparison per trigger"), detail: t("Put a second comparison in another trigger.") }); return; }
      const made = newCompare(store, host, index, trigger);
      if (!made) { api.ui.toast({ kind: "error", title: t("No free counter cells for the comparison") }); return; }
      store.commit(t("Add comparison"), () => store.list.map((tr, j) => (j !== index ? tr : { ...tr, conditions: [...conditions, ...made.conditions] })), { sidecar: { expansions: [...store.sidecar.expansions, made.expansion] } });
      return;
    }
    writeConditions(t("Add condition"), [...conditions, newCondition(api, pick, entities, query)]);
  }, { names: () => host.parseNames() }));
  root.append(condSection);

  /* ── Actions ── */
  const actions = liveActions(trigger);
  // The rows: every record on its own, a grouped entry's records as one, the title's Comment left out.
  const spans = actionSpans(actions).filter((s) => s.at !== ci);
  const shownActions = spans.map((s) => ({ a: actions[s.at], i: s.at, span: s }));
  const actSection = el("div", { className: "mg-section" }, el("div", { className: "mg-section-head" }, t("Actions"), el("span", { className: "grow" }), el("span", { className: "hint" }, `${actions.length}/${MAX_ACTIONS}`)));
  const writeActions = (label: string, next: ActionRecord[]) => replace(label, { ...trigger, actions: next });
  /** Swap the row at `pos` (in shown order) with its neighbour, both as whole spans. */
  const moveSpan = (pos: number, d: number) => {
    const to = pos + d;
    if (to < 0 || to >= shownActions.length) return;
    const a = shownActions[Math.min(pos, to)].span, b = shownActions[Math.max(pos, to)].span;
    if (a.at + a.count !== b.at) return;
    const next = [...actions.slice(0, a.at), ...actions.slice(b.at, b.at + b.count), ...actions.slice(a.at, a.at + a.count), ...actions.slice(b.at + b.count)];
    writeActions(t("Move action"), next);
  };
  for (const [pos, { a, i, span }] of shownActions.entries()) {
    if (span.group) {
      const records = actions.slice(i, i + span.count);
      const splice = (next: ActionRecord[]) => [...actions.slice(0, i), ...next, ...actions.slice(i + span.count)];
      actSection.append(renderGroupRow(ctx, i, span.group, records, at("action", i), {
        onChange: (recs) => writeActions(t("Edit action"), splice(recs)),
        onChangeWithText: (text, apply) => store.commit(t("Edit action"), (intern) => store.list.map((tr, j) => (j !== index ? tr : { ...tr, actions: splice(apply(intern(text))) }))),
        onRemove: () => writeActions(t("Remove action"), splice([])),
        onMove: (d) => moveSpan(pos, d),
        onToggle: () => writeActions(t("Toggle action"), splice(records.map((x) => setActionDisabled(x, !records.every((r) => r.flags & 2))))),
      }));
      continue;
    }
    const hook = hookOf(store, a);
    if (hook) {
      const sentence = el("span", { className: "mg-sentence" });
      renderHook(api, host, store, hook, sentence);
      // The definition goes only when no other trigger sets the same flag (a shared row left over from before duplicates got their own).
      const remove = api.ui.widgets.button("✕", { ghost: true, title: t("Remove"), onClick: () => store.commit(t("Remove build row"), () => store.list.map((tr, j) => (j !== index ? tr : { ...tr, actions: actions.filter((_, j2) => j2 !== i) })), sharedElsewhere(store.list, hook, index) ? {} : { sidecar: { builds: store.sidecar.builds.filter((b) => b.id !== hook.id) } }) });
      actSection.append(el("div", {}, el("div", { className: "mg-row", tabIndex: 0 }, sentence, el("span", { className: "mg-tools" }, remove))));
      continue;
    }
    const cx = counterExpansionOf(store, a);
    if (cx) {
      const sentence = el("span", { className: "mg-sentence" });
      renderCounterExpansion(api, host, store, cx, sentence);
      const remove = api.ui.widgets.button("✕", { ghost: true, title: t("Remove"), onClick: () => writeActions(t("Remove counter step"), actions.filter((_, j) => j !== i)) });
      actSection.append(el("div", {}, el("div", { className: "mg-row", tabIndex: 0 }, sentence, el("span", { className: "mg-tools" }, remove))));
      continue;
    }
    actSection.append(renderRow(ctx, "action", i, a, at("action", i), {
      onChange: (rec) => writeActions(t("Edit action"), actions.map((x, j) => (j === i ? rec : x))),
      onChangeWithText: (text, apply) => store.commit(t("Edit action"), (intern) => store.list.map((tr, j) => (j !== index ? tr : { ...tr, actions: actions.map((x, k) => (k === i ? apply(intern(text)) : x)) }))),
      onRemove: () => writeActions(t("Remove action"), actions.filter((_, j) => j !== i)),
      onMove: (d) => moveSpan(pos, d),
      onToggle: () => writeActions(t("Toggle action"), actions.map((x, j) => (j === i ? setActionDisabled(x, !(x.flags & 2)) : x))),
    }));
  }
  if (actions.length < MAX_ACTIONS) actSection.append(addRow(api, "action", ({ pick, entities, query }: Picked) => {
    if (pick.kind === "build") {
      if (pick.what === "chat" || pick.what === "scan" || pick.what === "key" || pick.what === "click" || pick.what === "mouseIn") return;
      // setloc, text, math, foreach, count, read, pick
      const made = newHook(host, store, pick.what, query, { unit: entities.find((e) => e.kind === "unit")?.value, location: entities.find((e) => e.kind === "location")?.value });
      if (!made) { api.ui.toast({ kind: "error", title: t("No free counter cell for the build row") }); return; }
      store.commit(t("Add build row"), () => store.list.map((tr, j) => (j !== index ? tr : { ...tr, actions: [...actions, made.action] })), { sidecar: { builds: made.builds } });
      return;
    }
    if (pick.kind === "expansion") {
      if (pick.what === "compare") return;
      const made = newCounterStep(store, host, pick.what);
      if (!made) { api.ui.toast({ kind: "error", title: t("No free counter cells for the step") }); return; }
      store.commit(t("Add counter step"), () => store.list.map((tr, j) => (j !== index ? tr : { ...tr, actions: [...actions, flagAction({ cell: made.flag })] })), { sidecar: { expansions: [...store.sidecar.expansions, made.expansion] } });
      return;
    }
    if (pick.kind === "native" && pick.type === ActionType.Comment) {
      // The first Comment is the title, so an empty one would only vanish into an empty title field.
      void api.ui.prompt(ci < 0 ? t("The trigger's name, shown by every trigger editor") : t("A note on this trigger; the game does nothing with it"), { title: t("Comment") }).then((text) => {
        if (!text?.trim()) return;
        store.commit(t("Add action"), (intern) => store.list.map((tr, j) => (j !== index ? tr : { ...tr, actions: [...liveActions(tr), { ...api.triggers.newAction(ActionType.Comment), text: intern(text.trim()) }] })));
      });
      return;
    }
    const made = newActions(api, pick, entities, query);
    if (actions.length + made.length > MAX_ACTIONS) { api.ui.toast({ kind: "info", title: t("No room for this row"), detail: t("It writes {n} records and the trigger has {free} action slots left.", { n: made.length, free: MAX_ACTIONS - actions.length }) }); return; }
    writeActions(t("Add action"), [...actions, ...made]);
  }, { names: () => host.parseNames() }));
  root.append(actSection);

  /* ── In plain words ── */
  const w = api.ui.widgets;
  const fold = w.fold({ text: t("In plain words"), open: store.showExplain });
  fold.addEventListener("toggle", () => { store.showExplain = fold.open; });
  const x = explain(trigger, index, store.list, {
    conditions: conditionWords(api, host, store, index, trigger),
    actions: actionWords(api, host, store, trigger),
    player: (g) => groups.find((g2) => g2.value === g)?.label ?? String(g),
    perPlayer: perPlayer ? { players: perPlayer.players, placeholder: perPlayer.placeholder } : null,
    everyFrame: !!store.sidecar.settings.everyFrame,
    anchorOf: (i) => store.anchorOf(i),
  });
  const words = el("div", { className: "mg-explain" }, ...x.lines.map((line) => el("p", {}, line)));
  const shared = x.refs.filter((r) => r.others.length);
  if (shared.length) {
    const refs = el("div", { className: "mg-refs" });
    for (const r of shared) refs.append(refLine(r));
    words.append(refs);
  } else if (x.refs.length) words.append(el("div", { className: "mg-refs" }, el("span", {}, t("No other trigger uses the switches, counters or locations this one touches."))));
  fold.body.append(words);
  root.append(fold);

  function refLine(r: Ref): HTMLElement {
    const label = r.kind === "switch" ? namer.switch(r.id) : r.kind === "counter" ? cellLabel(cellOf(r.id), namer) : r.kind === "location" ? namer.location(r.id) : r.kind === "timer" ? t("The countdown timer") : t("memory at 0x{addr}", { addr: r.id.toString(16).toUpperCase() });
    const verbs = r.kind === "switch" || r.kind === "timer" ? { writes: t("set by"), reads: t("read by"), both: t("set and read by") } : r.kind === "location" ? { writes: t("moved by"), reads: t("used by"), both: t("moved and used by") } : { writes: t("changed by"), reads: t("read by"), both: t("changed and read by") };
    const line = el("div", { className: "mg-ref" }, el("b", {}, label));
    for (const use of ["writes", "reads", "both"] as const) {
      const who = r.others.filter((o) => o.use === use);
      if (!who.length) continue;
      line.append(el("span", {}, verbs[use]));
      who.forEach((o, k) => line.append(el("button", { type: "button", className: "mg-sim-link", onclick: () => store.select(o.index) }, titleOf(api, host, store, o.index) + (k < who.length - 1 ? "," : ""))));
    }
    return line;
  }
}

/** A fresh condition for a pick: StarEdit's defaults for a native one, the entry's for an EUD one. */
export function newCondition(api: PluginApi, pick: Pick, entities: Entity[] = [], query = ""): ConditionRecord {
  if (pick.kind === "native") return fillCondition(api.triggers.newCondition(pick.type), entities);
  if (pick.kind === "expansion" || pick.kind === "build") throw new Error("not a record of its own");
  const e = pick.entry;
  if (entities.length) return lowerCondition(fillEud(e, "condition", entities, query));
  const args: Record<string, number> = {};
  for (const a of e.args) args[a.name] = 0;
  return lowerCondition({ entry: e, args, value: e.value?.choices ? e.value.choices[0].value : e.value?.min ?? 0, op: enumerated(e) ? Comparison.Exactly : Comparison.AtLeast });
}

/** The records for a pick: one for a native action or a plain entry, the parts of a grouped entry. */
export function newActions(api: PluginApi, pick: Pick, entities: Entity[] = [], query = ""): ActionRecord[] {
  if (pick.kind === "native") return [fillAction(api.triggers.newAction(pick.type), entities)];
  if (pick.kind === "expansion" || pick.kind === "build") throw new Error("not a record of its own");
  const e = pick.entry;
  if (entities.length) return lowerActions(fillEud(e, "action", entities, query));
  const args: Record<string, number> = {};
  for (const a of e.args) args[a.name] = 0;
  return lowerActions({ entry: e, args, value: e.value?.choices ? e.value.choices[0].value : e.value?.min ?? 0, op: SetModifier.SetTo });
}

export const newAction = (api: PluginApi, pick: Pick, entities: Entity[] = [], query = ""): ActionRecord => newActions(api, pick, entities, query)[0];
