/**
 * The right pane: the open trigger — its title (the Comment action), its owners, its
 * conditions and actions as rows with an add row under each, and the problems the
 * checks found. A trigger inside another plugin's claimed run shows that plugin's
 * sentence and its Open button instead.
 */
import type { PluginApi, ActionRecord, ConditionRecord, TriggerRecord } from "@scm-js/plugin-api";
import { ActionType, ConditionType, Comparison, SetModifier, MAX_ACTIONS, MAX_CONDITIONS, PLAYER_GROUP_COUNT } from "../../vendor/triggers";
import { enumerated } from "../catalogue";
import { check, type Problem } from "../model/checks";
import { lowerAction, lowerCondition } from "../model/eud";
import { commentIndex, liveActions, liveConditions, owners, setActionDisabled, setConditionDisabled, setOwners } from "../model/records";
import { cellKey, playerSlots } from "../model/counters";
import type { Host } from "./host";
import { addRow, type Pick } from "./palette";
import { pickChoice } from "./chips";
import { renderRow, type RowContext } from "./rows";
import { compareOf, counterExpansionOf, newCompare, newCounterStep, renderCompare, renderCounterExpansion } from "./expansionRows";
import { flagAction } from "../model/expansions";
import type { Store } from "./store";

export interface EditorDeps {
  api: PluginApi;
  host: Host;
  store: Store;
}

/** Fill `root` with the editor for the selected trigger. */
export function renderEditor(deps: EditorDeps, root: HTMLElement): void {
  const { api, host, store } = deps;
  const el = api.ui.el;
  const t = api.i18n.t;
  root.replaceChildren();
  const index = store.selected;
  if (index === null || !store.list[index]) {
    root.append(el("div", { className: "mg-empty" }, store.list.length ? t("Pick a trigger on the left, or add one.") : t("This map has no triggers yet. Add one with New.")));
    return;
  }
  const trigger = store.list[index];
  const claim = host.claims(store.list).find((c) => index >= c.start && index < c.start + c.count);
  if (claim && claim.pluginId !== api.plugin.id) {
    root.append(el("div", { className: "mg-locked" },
      el("div", {}, t("Generated by {what}: edit it there, not here.", { what: claim.label })),
      el("div", { className: "row" }, api.ui.widgets.button(t("Open {plugin}", { plugin: claim.badge }), { onClick: () => api.commands.run(`${claim.pluginId}.open`, { index }) })),
    ));
    return;
  }

  const namer = host.namer(store.sidecar);
  const extra = host.extra();
  const ctx: RowContext = { api, host, store, namer, extra, triggerIndex: index };
  const claimedCells = new Set<number>();
  for (const c of host.claims(store.list)) {
    if (c.pluginId === api.plugin.id) continue;
    for (let i = c.start; i < c.start + c.count; i++) {
      const tr = store.list[i];
      if (!tr) continue;
      const own = owners(tr);
      for (const cc of tr.conditions) if (cc.type === ConditionType.Deaths && cc.player < PLAYER_GROUP_COUNT && cc.unitId < 228) for (const p of playerSlots(cc.player, own)) claimedCells.add(cellKey(p, cc.unitId));
      for (const a of tr.actions) if (a.type === ActionType.SetDeaths && a.player < PLAYER_GROUP_COUNT && a.unitId < 228) for (const p of playerSlots(a.player, own)) claimedCells.add(cellKey(p, a.unitId));
    }
  }
  const perPlayer = store.sidecar.expansions.find((x): x is Extract<typeof x, { kind: "forEachPlayer" }> => x.kind === "forEachPlayer" && x.anchor.i === store.cleanIndex(index));
  const problems = check(trigger, { everyFrame: store.sidecar.settings.everyFrame, locationExists: (n) => host.locationExists(n), stringExists: (i) => host.stringExists(i), wavPresent: (i) => host.wavPresent(i), claimedCells, template: !!perPlayer });
  const general = problems.filter((p) => !p.at);
  const at = (kind: "condition" | "action", i: number): Problem[] => problems.filter((p) => p.at?.kind === kind && p.at.index === i);

  const replace = (label: string, next: TriggerRecord) => store.replace(index, next, label);

  /* ── Title ── */
  const ci = commentIndex(trigger);
  const titleText = ci >= 0 ? namer.string(trigger.actions[ci].text) ?? "" : "";
  const title = el("input", { className: "input", type: "text", placeholder: t("Untitled trigger — type a name"), value: titleText, title: t("The trigger's name, kept as its Comment action so every editor shows it") }) as HTMLInputElement;
  const commitTitle = () => {
    const text = title.value.trim();
    if (text === titleText) return;
    store.commit(t("Rename trigger"), (intern) => store.list.map((tr, i) => {
      if (i !== index) return tr;
      const actions = tr.actions.filter((a) => a.type !== ActionType.Comment);
      if (text) actions.unshift({ ...api.triggers.newAction(ActionType.Comment), text: intern(text) });
      return { ...tr, actions };
    }));
  };
  title.addEventListener("change", commitTitle);
  title.addEventListener("keydown", (e) => { if (e.key === "Enter") { e.preventDefault(); title.blur(); } });
  root.append(el("div", { className: "mg-titlebar" }, title));

  /* ── Players ── */
  const own = owners(trigger);
  const playersRow = el("div", { className: "mg-players" }, el("span", { className: "hint" }, t("Runs for")));
  const groups = host.playerGroups();
  const players = host.players();
  for (const g of own) {
    const chip = el("button", { type: "button", className: "mg-chip", title: t("Click to remove") }, g < 12 && players[g]?.color ? el("span", { className: "mg-dot", style: `background:${players[g].color}` }) : null, groups.find((x) => x.value === g)?.label ?? String(g)) as HTMLButtonElement;
    chip.addEventListener("click", () => replace(t("Change owners"), setOwners(trigger, own.filter((x) => x !== g))));
    playersRow.append(chip);
  }
  const addOwner = el("button", { type: "button", className: "mg-chip", title: t("Add a player or group") }, "+") as HTMLButtonElement;
  addOwner.addEventListener("click", () => pickChoice(api, addOwner, groups.filter((g) => !own.includes(g.value)).map((g) => ({ value: g.value, label: g.label, color: g.value < 12 ? players[g.value]?.color ?? null : undefined })), (v) => replace(t("Change owners"), setOwners(trigger, [...own, v])), { width: 220 }));
  playersRow.append(addOwner);
  if (perPlayer) {
    playersRow.replaceChildren(el("span", { className: "hint" }, t("Runs once for each of")), ...perPlayer.players.map((p) => el("span", { className: "mg-chip" }, players[p]?.color ? el("span", { className: "mg-dot", style: `background:${players[p].color}` }) : null, groups.find((x) => x.value === p)?.label ?? String(p))), el("span", { className: "hint" }, t("with {group} standing for the player", { group: groups.find((x) => x.value === perPlayer.placeholder)?.label ?? "" })));
  }
  root.append(playersRow);
  for (const p of general) root.append(el("div", { className: `mg-problem ${p.level}`, style: "padding-left:6px" }, p.text));

  /* ── Conditions ── */
  const conditions = liveConditions(trigger);
  const condSection = el("div", { className: "mg-section" }, el("div", { className: "mg-section-head" }, t("Conditions"), el("span", { className: "grow" }), el("span", { className: "hint" }, `${conditions.length}/${MAX_CONDITIONS}`)));
  const writeConditions = (label: string, next: ConditionRecord[]) => replace(label, { ...trigger, conditions: next });
  const cmp = compareOf(store, index, trigger);
  conditions.forEach((c, i) => {
    if (cmp && cmp.rows.includes(i)) {
      if (i !== cmp.rows[0]) return;
      const sentence = el("span", { className: "mg-sentence" });
      renderCompare(api, host, store, index, trigger, cmp, sentence);
      const remove = api.ui.widgets.button("✕", { ghost: true, title: t("Remove"), onClick: () => store.commit(t("Remove comparison"), () => store.list.map((tr, j) => (j !== index ? tr : { ...tr, conditions: conditions.filter((_, k) => !cmp.rows.includes(k)) })), { sidecar: { expansions: store.sidecar.expansions.filter((x) => x.id !== cmp.x.id) } }) });
      condSection.append(el("div", {}, el("div", { className: "mg-row", tabIndex: 0 }, sentence, el("span", { className: "mg-tools" }, remove))));
      return;
    }
    condSection.append(renderRow(ctx, "condition", i, c, at("condition", i), {
      onChange: (rec) => writeConditions(t("Edit condition"), conditions.map((x, j) => (j === i ? rec : x))),
      onChangeWithText: (text, apply) => store.commit(t("Edit condition"), (intern) => store.list.map((tr, j) => (j !== index ? tr : { ...tr, conditions: conditions.map((x, k) => (k === i ? apply(intern(text)) : x)) }))),
      onRemove: () => writeConditions(t("Remove condition"), conditions.filter((_, j) => j !== i)),
      onMove: (d) => { const to = i + d; if (to < 0 || to >= conditions.length) return; const next = [...conditions]; [next[i], next[to]] = [next[to], next[i]]; writeConditions(t("Move condition"), next); },
      onToggle: () => writeConditions(t("Toggle condition"), conditions.map((x, j) => (j === i ? setConditionDisabled(x, !(x.flags & 2)) : x))),
    }));
  });
  if (conditions.length < MAX_CONDITIONS) condSection.append(addRow(api, "condition", (pick) => {
    if (pick.kind === "expansion") {
      if (cmp) { api.ui.toast({ kind: "info", title: t("One comparison per trigger"), detail: t("Put a second comparison in another trigger.") }); return; }
      const made = newCompare(store, host, index, trigger);
      if (!made) { api.ui.toast({ kind: "error", title: t("No free counter cells for the comparison") }); return; }
      store.commit(t("Add comparison"), () => store.list.map((tr, j) => (j !== index ? tr : { ...tr, conditions: [...conditions, ...made.conditions] })), { sidecar: { expansions: [...store.sidecar.expansions, made.expansion] } });
      return;
    }
    writeConditions(t("Add condition"), [...conditions, newCondition(api, pick)]);
  }));
  root.append(condSection);

  /* ── Actions ── */
  const actions = liveActions(trigger);
  const shownActions = actions.map((a, i) => ({ a, i })).filter(({ a }) => a.type !== ActionType.Comment);
  const actSection = el("div", { className: "mg-section" }, el("div", { className: "mg-section-head" }, t("Actions"), el("span", { className: "grow" }), el("span", { className: "hint" }, `${actions.length}/${MAX_ACTIONS}`)));
  const writeActions = (label: string, next: ActionRecord[]) => replace(label, { ...trigger, actions: next });
  for (const { a, i } of shownActions) {
    const cx = counterExpansionOf(store, a);
    if (cx) {
      const sentence = el("span", { className: "mg-sentence" });
      renderCounterExpansion(api, host, store, cx, sentence);
      const remove = api.ui.widgets.button("✕", { ghost: true, title: t("Remove"), onClick: () => writeActions(t("Remove counter step"), actions.filter((_, j) => j !== i)) });
      actSection.append(el("div", {}, el("div", { className: "mg-row", tabIndex: 0 }, sentence, el("span", { className: "mg-tools" }, remove))));
      continue;
    }
    actSection.append(renderRow(ctx, "action", i, a, at("action", i), {
      onChange: (rec) => writeActions(t("Edit action"), actions.map((x, j) => (j === i ? rec : x))),
      onChangeWithText: (text, apply) => store.commit(t("Edit action"), (intern) => store.list.map((tr, j) => (j !== index ? tr : { ...tr, actions: actions.map((x, k) => (k === i ? apply(intern(text)) : x)) }))),
      onRemove: () => writeActions(t("Remove action"), actions.filter((_, j) => j !== i)),
      onMove: (d) => {
        const order = shownActions.map((x) => x.i);
        const pos = order.indexOf(i);
        const to = pos + d;
        if (to < 0 || to >= order.length) return;
        const next = [...actions];
        [next[order[pos]], next[order[to]]] = [next[order[to]], next[order[pos]]];
        writeActions(t("Move action"), next);
      },
      onToggle: () => writeActions(t("Toggle action"), actions.map((x, j) => (j === i ? setActionDisabled(x, !(x.flags & 2)) : x))),
    }));
  }
  if (actions.length < MAX_ACTIONS) actSection.append(addRow(api, "action", (pick) => {
    if (pick.kind === "expansion") {
      if (pick.what === "compare") return;
      const made = newCounterStep(store, host, pick.what);
      if (!made) { api.ui.toast({ kind: "error", title: t("No free counter cells for the step") }); return; }
      store.commit(t("Add counter step"), () => store.list.map((tr, j) => (j !== index ? tr : { ...tr, actions: [...actions, flagAction({ cell: made.flag })] })), { sidecar: { expansions: [...store.sidecar.expansions, made.expansion] } });
      return;
    }
    writeActions(t("Add action"), [...actions, newAction(api, pick)]);
  }));
  root.append(actSection);
}

/** A fresh condition for a pick: StarEdit's defaults for a native one, the entry's for an EUD one. */
export function newCondition(api: PluginApi, pick: Pick): ConditionRecord {
  if (pick.kind === "native") return api.triggers.newCondition(pick.type);
  if (pick.kind === "expansion") throw new Error("an expansion is not a record");
  const e = pick.entry;
  const args: Record<string, number> = {};
  for (const a of e.args) args[a.name] = 0;
  return lowerCondition({ entry: e, args, value: e.value?.choices ? e.value.choices[0].value : e.value?.min ?? 0, op: enumerated(e) ? Comparison.Exactly : Comparison.AtLeast });
}

export function newAction(api: PluginApi, pick: Pick): ActionRecord {
  if (pick.kind === "native") return api.triggers.newAction(pick.type);
  if (pick.kind === "expansion") throw new Error("an expansion is not a record");
  const e = pick.entry;
  const args: Record<string, number> = {};
  for (const a of e.args) args[a.name] = 0;
  return lowerAction({ entry: e, args, value: e.value?.choices ? e.value.choices[0].value : e.value?.min ?? 0, op: SetModifier.SetTo });
}
