/**
 * `python/magenta.py` — the euddraft plugin that turns Magenta's build records into eudplib
 * code — as a TypeScript string, so the plugin can hand it to the eudplib library plugin at
 * build time without a loader. Run after editing the Python: `npx tsx scripts/embed-python.mts`.
 * `tests/python.test.ts` fails when the two drift.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
const root = join(import.meta.dirname, "..");
const py = readFileSync(join(root, "python/magenta.py"), "utf8");
writeFileSync(join(root, "src/generated/magentaPy.ts"), `// Generated by scripts/embed-python.mts from python/magenta.py — do not edit.\nexport const MAGENTA_PY: string = ${JSON.stringify(py)};\n`);
console.log(`src/generated/magentaPy.ts: ${py.length} chars`);
